<a href="https://colab.research.google.com/github/kuheli31/Fake-News-Detector/blob/main/Fake_News_New.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
import re
import string
import requests
from requests.utils import quote
from urllib.parse import quote

Enter the news to verify if its real or fake

In [2]:
import spacy


nlp = spacy.load("en_core_web_sm")
news = input("Enter the news to verify if it is real or fake: ")
doc = nlp(news)
keywords = [token.text for token in doc if token.pos_ in ["PROPN", "NOUN"] and len(token.text) > 2]
seen = set()
keywords = [k for k in keywords if not (k.lower() in seen or seen.add(k.lower()))]
news_check = keywords[:4]
print("Extracted Keywords for Search:", " ".join(news_check))

Enter the news to verify if it is real or fake: India's win over Iran in the gold.
Extracted Keywords for Search: India win Iran gold

# **Data Collection**

**G-News API (Real News)**

In [3]:
#Real time news api (https://gnews.io/dashboard) -- 100 requests per day
news_api_key = 'd2b27a1e3f818564545508b6c744d24a'
#Endpoints are -> {search , top-headlines}
endpoint = 'search'
#Parameters are -> {The topic the user want to search}
question = " ".join(news_check)
parameters = f'q={quote(question)}&lang=en&max=5'
#Example (try this link to understand the url)-> https://gnews.io/api/v4/top-headlines?q=modi&lang=en&max=5&apikey=d2b27a1e3f818564545508b6c744d24a
news_api_url = f'https://gnews.io/api/v4/{endpoint}?{parameters}&apikey={news_api_key}'

response = requests.get(news_api_url)
data = response.json()

if 'articles' in data:
    for article in data['articles']:
        print(f"Published Time: {article['publishedAt']}")
        print(f"Title: {article['title']}")
        print(f"Description: {article['description']}")
        print(f"Image: {article['image']}")
        print(f"Content: {article['content']}")
        print(f"Source Name: {article['source']['name']}")
        print(f"Source URL: {article['source']['url']}")
        print(f"Source Country: {article['source']['country']}")
        print(f"URL: {article['url']}\n")
 # Extract article details into a list of dicts
    articles_data = []
    for article in data['articles']:
        articles_data.append({
            "Published Time": article.get('publishedAt'),
            "Title": article.get('title'),
            "Description": article.get('description'),
            "Image URL": article.get('image'),
            "Content": article.get('content'),
            "Source Name": article['source'].get('name'),
            "Source URL": article['source'].get('url'),
            "Source Country": article['source'].get('country'),
            "Article URL": article.get('url')
        })

    # Create DataFrame
    df = pd.DataFrame(articles_data)

    # Save as CSV
    df.to_csv('gnews.csv', index=False, encoding='utf-8')

    print("✅ Articles successfully saved to 'gnews.csv'")

else:
    print(data)

Published Time: 2026-09-27T08:47:17Z
Title: "I still can't believe it": Prachi Choudhary after clinching women's 400m bronze at Asian Games
Description: Prachi Choudhary claimed the bronze with a timing of 53.21 seconds. Bahrain's Salma Naser claimed the gold medal with a Games Record time of 49.20 seconds, while Iran's Zahra Zarei Manoujan took silver after clocking 52.38 seconds. India's Kiran finished fifth in 53.41 seconds. Following the medal win, Prachi described the moment as something she had been working for since a long time.
Image: https://www.tribuneindia.com/sortd-service/imaginary/v22-01/jpg/large/high?url=dGhldHJpYnVuZS1zb3J0ZC1wcm8tcHJvZC1zb3J0ZC9tZWRpYTBmZDNlMTEwLWJhNTAtMTFmMS1iN2M0LWQ5MzYzYTY1OTBjNy5qcGc=
Content: New Delhi [India], September 27 (ANI): India added to its medal tally at the Asian Games on Saturday as Prachi Choudhary claimed bronze in the final of the women’s 400m, delivering one of the standout performances of the night for the Indian continge... [2673 chars]
Source Name: The Tribune
Source URL: https://www.tribuneindia.com
Source Country: in
URL: https://www.tribuneindia.com/news/sports/i-still-cant-believe-it-prachi-choudhary-after-clinching-womens-400m-bronze-at-asian-games/

Published Time: 2026-09-27T08:45:34Z
Title: "I still can't believe it": Prachi Choudhary after clinching women's 400m bronze at Asian Games
Description: Prachi Choudhary claimed the bronze with a timing of 53.21 seconds. Bahrain's Salma Naser claimed the gold medal with a Games Record time of 49.20 seconds, while Iran's Zahra Zarei Manoujan took silver after clocking 52.38 seconds. India's Kiran finished fifth in 53.41 seconds. Following the medal win, Prachi described the moment as something she had been working for since a long time.
Image: https://d3lzcn6mbbadaf.cloudfront.net/media/details/__sized__/ANI-20260927084517-thumbnail-320x180-70.jpg
Content: New Delhi [India], September 27 (ANI): India added to its medal tally at the Asian Games on Saturday as Prachi Choudhary claimed bronze in the final of the women’s 400m, delivering one of the standout performances of the night for the Indian continge... [1268 chars]
Source Name: ANI (Asian News International)
Source URL: https://www.aninews.in
Source Country: in
URL: https://www.aninews.in/news/sports/others/i-still-cant-believe-it-prachi-choudhary-after-clinching-womens-400m-bronze-at-asian-games20260927141534/

Published Time: 2026-09-26T17:10:25Z
Title: India Beat Iran In Both Kabaddi Finals To Win Golden Double At Asian Games 2026
Description: India completed a kabaddi golden double at the Asian Games 2026 as the women beat Iran 37-34 and the men secured a 40-34 win. Both teams retained their titles, adding two more gold medals to India’s tally in Aichi-Nagoya.
Image: https://sm.mashable.com/mashable_in/seo/default/indiakabbadi_jut6.jpg
Content: India completed a golden double in kabaddi at the Asian Games 2026 on Saturday, with both the men’s and women’s teams defeating Iran in their respective finals in Aichi-Nagoya, Japan.
The women’s team started the celebrations with a hard-fought 37-34... [2339 chars]
Source Name: Mashable India
Source URL: https://in.mashable.com
Source Country: in
URL: https://in.mashable.com/sports/114326/india-beat-iran-in-both-kabaddi-finals-to-win-golden-double-at-asian-games-2026

Published Time: 2026-09-26T13:51:00Z
Title: India maintain choke-hold on Asiad Kabaddi gold; Both men and women finish on top
Description: India's kabaddi teams delivered stellar performances at the Asian Games, overpowering Iran to secure their gold medals once again. The men edged out a 40-34 victory, thanks to smart strategic modifications during the game. The women's team followed suit with a close 37-34 win, taking advantage of Iran's left flank weaknesses. Their collective experience propelled them to defend their titles with flair.
Image: https://img.etimg.com/thumb/msid-134505784,width-1200,height-630,imgsize-222378,overlay-economictimes/articleshow.jpg
Content: Synopsis
India's kabaddi teams delivered stellar performances at the Asian Games, overpowering Iran to secure their gold medals once again. The men edged out a 40-34 victory, thanks to smart strategic modifications during the game. The women's team f... [6016 chars]
Source Name: The Economic Times
Source URL: https://economictimes.indiatimes.com
Source Country: in
URL: https://economictimes.indiatimes.com/news/sports/other-sports/india-maintain-choke-hold-on-asiad-kabaddi-gold-both-men-and-women-finish-on-top/articleshow/134505714.cms

Published Time: 2026-09-26T12:52:34Z
Title: Prachi Choudhary Win Bronze In Women's 400m For India At Asian Games 2026
Description: Salwa Naser of Bahrain bagged the gold medal with a new Asian Games record of 49.20 seconds, while Zahra Manoujan Zarei of Iran won the silver medal with a timing of 52.38 seconds.
Image: https://images.news18.com/ibnlive/uploads/2026/09/Prachi-Choudhary-wins-bronze-for-India-in-womens-400m-2026-09-09b7f4b041061f2bd8fad762010d8457-1200x675.jpg
Content: Last Updated:September 26, 2026, 18:27 IST
Salwa Naser of Bahrain bagged the gold medal with a new Asian Games record of 49.20 seconds, while Zahra Manoujan Zarei of Iran won the silver medal with a timing of 52.38 seconds.
Prachi Choudhary has won a... [2211 chars]
Source Name: News18
Source URL: https://www.news18.com
Source Country: in
URL: https://www.news18.com/sports/other-sports/prachi-choudhary-win-bronze-in-womens-400m-for-india-at-asian-games-ws-l-10354543.html

✅ Articles successfully saved to 'gnews.csv'

**BlueSky API**

In [15]:
pip install atproto

Collecting atproto
  Downloading atproto-0.0.72-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: click<9,>=8.1.3 in /usr/local/lib/python3.13/dist-packages (from atproto) (8.5.0)
Requirement already satisfied: cryptography<51,>=41.0.7 in /usr/local/lib/python3.13/dist-packages (from atproto) (50.0.1)
Collecting dnspython<3,>=2.4.0 (from atproto)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: httpx<0.29.0,>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from atproto) (0.28.1)
Collecting libipld<4,>=3.0.1 (from atproto)
  Downloading libipld-3.4.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.4 kB)
Requirement already satisfied: pydantic<3,>=2.7 in /usr/local/lib/python3.13/dist-packages (from atproto) (2.13.5)
Requirement already satisfied: typing-extensions<5,>=4.8.0 in /usr/local/lib/python3.13/dist-packages (from atproto) (4.16.0)
Requirement already satisfied: websockets<18,>=15 in /usr/local/lib/python3.13/dist-packages (from atproto) (15.0.1)
Requirement already satisfied: zstandard<0.26.0,>=0.24.0 in /usr/local/lib/python3.13/dist-packages (from atproto) (0.25.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography<51,>=41.0.7->atproto) (2.1.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<0.29.0,>=0.25.0->atproto) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<0.29.0,>=0.25.0->atproto) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<0.29.0,>=0.25.0->atproto) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<0.29.0,>=0.25.0->atproto) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<0.29.0,>=0.25.0->atproto) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2.7->atproto) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2.7->atproto) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2.7->atproto) (0.4.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography<51,>=41.0.7->atproto) (3.0)
Downloading atproto-0.0.72-py3-none-any.whl (623 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 623.2/623.2 kB 23.6 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 16.0 MB/s eta 0:00:00
Downloading libipld-3.4.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (286 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 286.0/286.0 kB 15.6 MB/s eta 0:00:00
Installing collected packages: libipld, dnspython, atproto
Successfully installed atproto-0.0.72 dnspython-2.8.0 libipld-3.4.1

In [22]:
# ============================================
# Bluesky API - Search Posts
# ============================================

import requests
import pandas as pd


# --------------------------------------------
# Search query
# --------------------------------------------

question = " ".join(news_check).strip()


# --------------------------------------------
# Bluesky public API endpoint
# --------------------------------------------

SEARCH_URL = "https://api.bsky.app/xrpc/app.bsky.feed.searchPosts"


# --------------------------------------------
# Check query
# --------------------------------------------

if not question:

    print("ERROR: Search query is required.")

else:

    try:

        # ------------------------------------
        # API parameters
        # ------------------------------------

        params = {
            "q": question,
            "limit": 10
        }


        # ------------------------------------
        # API request
        # ------------------------------------

        response = requests.get(
            SEARCH_URL,
            params=params,
            timeout=10
        )


        # ------------------------------------
        # Check response
        # ------------------------------------

        response.raise_for_status()

        data = response.json()

        posts = data.get("posts", [])


        # ------------------------------------
        # No posts found
        # ------------------------------------

        if not posts:

            print("\nNo Bluesky posts found for that query.")

            # Create empty DataFrame
            df_bluesky = pd.DataFrame()


        # ------------------------------------
        # Posts found
        # ------------------------------------

        else:

            print("\n--- Found Bluesky Posts ---\n")

            post_rows = []


            # --------------------------------
            # Process each post
            # --------------------------------

            for post in posts:

                # ----------------------------
                # Post information
                # ----------------------------

                record = post.get("record", {})
                author = post.get("author", {})

                post_text = record.get("text")
                created_at = record.get("createdAt")


                # ----------------------------
                # Author information
                # ----------------------------

                author_did = author.get("did")

                author_handle = author.get("handle")

                author_display_name = author.get(
                    "displayName"
                )

                author_avatar = author.get(
                    "avatar"
                )


                # ----------------------------
                # Post URI
                # ----------------------------

                post_uri = post.get("uri")


                # ----------------------------
                # Create post URL
                # ----------------------------

                if author_handle and post_uri:

                    post_id = post_uri.split("/")[-1]

                    post_url = (
                        f"https://bsky.app/profile/"
                        f"{author_handle}/post/{post_id}"
                    )

                else:

                    post_url = None


                # ----------------------------
                # Engagement information
                # ----------------------------

                likes = post.get(
                    "likeCount",
                    0
                )

                reposts = post.get(
                    "repostCount",
                    0
                )

                replies = post.get(
                    "replyCount",
                    0
                )

                quotes = post.get(
                    "quoteCount",
                    0
                )


                # ----------------------------
                # Author URL
                # ----------------------------

                if author_handle:

                    author_url = (
                        f"https://bsky.app/profile/"
                        f"{author_handle}"
                    )

                else:

                    author_url = None


                # ----------------------------
                # Print information
                # ----------------------------

                print(
                    f"Published Time: {created_at}"
                )

                print(
                    f"Post Text: {post_text}"
                )

                print(
                    f"Author: "
                    f"{author_display_name} "
                    f"(@{author_handle})"
                )

                print(
                    f"Author DID: {author_did}"
                )

                print(
                    f"Author Profile Image: "
                    f"{author_avatar}"
                )

                print(
                    f"Author URL: {author_url}"
                )

                print(
                    f"Post URL: {post_url}"
                )

                print(
                    f"Likes: {likes}"
                )

                print(
                    f"Reposts: {reposts}"
                )

                print(
                    f"Replies: {replies}"
                )

                print(
                    f"Quotes: {quotes}"
                )

                print("\n")


                # ----------------------------
                # Store post information
                # ----------------------------

                post_rows.append({

                    "Published Time": created_at,

                    "Post Text": post_text,

                    "Author Name":
                        author_display_name,

                    "Author Handle":
                        author_handle,

                    "Author DID":
                        author_did,

                    "Author Profile Image":
                        author_avatar,

                    "Author URL":
                        author_url,

                    "Post URL":
                        post_url,

                    "Likes":
                        likes,

                    "Reposts":
                        reposts,

                    "Replies":
                        replies,

                    "Quotes":
                        quotes
                })


            # --------------------------------
            # Create DataFrame
            # --------------------------------

            df_bluesky = pd.DataFrame(
                post_rows
            )


            # --------------------------------
            # Save DataFrame to CSV
            # --------------------------------

            df_bluesky.to_csv(
                "bluesky_posts.csv",
                index=False,
                encoding="utf-8"
            )


            print(
                "✅ Bluesky posts successfully "
                "saved to 'bluesky_posts.csv'"
            )


            # --------------------------------
            # Display DataFrame
            # --------------------------------

            print("\n--- Bluesky DataFrame ---\n")

            display(df_bluesky)


    # ----------------------------------------
    # HTTP errors
    # ----------------------------------------

    except requests.exceptions.HTTPError as e:

        print(
            "\n--- BLUESKY API ERROR ---"
        )

        print(
            f"HTTP Error: {e}"
        )


    # ----------------------------------------
    # Connection errors
    # ----------------------------------------

    except requests.exceptions.RequestException as e:

        print(
            "\n--- CONNECTION ERROR ---"
        )

        print(
            f"Error details: {e}"
        )


    # ----------------------------------------
    # Other errors
    # ----------------------------------------

    except Exception as e:

        print(
            "\nAn unexpected error occurred."
        )

        print(
            f"Error details: {e}"
        )

--- Found Bluesky Posts ---

Published Time: 2026-09-26T17:10:25.000Z
Post Text:
Author: Mashable India [Unofficial] (@in.mashable.com.web.brid.gy)
Author DID: did:plc:tkzj743ruh5itf2pov2q5txv
Author Profile Image: https://cdn.bsky.app/img/avatar/plain/did:plc:tkzj743ruh5itf2pov2q5txv/bafkreiaajie5hdpgbly5yopoisnlwz74khfw5sozjljda3dfhahzta7z4i
Author URL: https://bsky.app/profile/in.mashable.com.web.brid.gy
Post URL: https://bsky.app/profile/in.mashable.com.web.brid.gy/post/3mwgxvjs6y4z2
Likes: 0
Reposts: 0
Replies: 0
Quotes: 0


Published Time: 2026-09-26T16:07:43Z
Post Text: Asian Games 2026 Day 7: India win seven medals as kabaddi teams deliver gold double in action-packed Saturday | Asian Games 2026 News

L-R: Joshna Chinappa, Prachi Choudhary and Tajinderpal Singh Toor NEW DELHI: India enjoyed one of its most productive days at the Asian Games 2026 on Saturday,…
Author: HFG INSIDER (@health897.bsky.social)
Author DID: did:plc:euogifoh4mj52xvkbqcfqtti
Author Profile Image: https://cdn.bsky.app/img/avatar/plain/did:plc:euogifoh4mj52xvkbqcfqtti/bafkreigera6aivibhahaismc5v6syf3ze2kfy6wlwura3fl4glt6xybo7q
Author URL: https://bsky.app/profile/health897.bsky.social
Post URL: https://bsky.app/profile/health897.bsky.social/post/3mwgo6bmgbe26
Likes: 0
Reposts: 0
Replies: 0
Quotes: 0


Published Time: 2026-09-26T10:55:45.726Z
Post Text: India beat Iran to win ninth Gold medal in men's #kabaddi, www.newsinc24.com/news/india-b...
Author:  (@newsinc24.bsky.social)
Author DID: did:plc:6qomd7wrtbnrjq5p3cww7fuc
Author Profile Image: https://cdn.bsky.app/img/avatar/plain/did:plc:6qomd7wrtbnrjq5p3cww7fuc/bafkreihz6ztatoffvfbys5scxz4skrrvat66pymhbyzvmjxng5nmargrxq
Author URL: https://bsky.app/profile/newsinc24.bsky.social
Post URL: https://bsky.app/profile/newsinc24.bsky.social/post/3mwg4qglslk2f
Likes: 0
Reposts: 0
Replies: 0
Quotes: 0


Published Time: 2026-09-26T09:36:23.000Z
Post Text:
Author: Mashable India [Unofficial] (@in.mashable.com.web.brid.gy)
Author DID: did:plc:tkzj743ruh5itf2pov2q5txv
Author Profile Image: https://cdn.bsky.app/img/avatar/plain/did:plc:tkzj743ruh5itf2pov2q5txv/bafkreiaajie5hdpgbly5yopoisnlwz74khfw5sozjljda3dfhahzta7z4i
Author URL: https://bsky.app/profile/in.mashable.com.web.brid.gy
Post URL: https://bsky.app/profile/in.mashable.com.web.brid.gy/post/3mwg2qavenq52
Likes: 0
Reposts: 0
Replies: 0
Quotes: 0


Published Time: 2026-09-25T18:59:24Z
Post Text: Asian Games 2026 Kabaddi: India Storm Into Men’s Final After 66-28 Win Over Thailand | Check Final Date, Time, Opponent And Live Streaming

India reached the Asian Games 2026 men’s kabaddi final after a dominant 66-28 semifinal win over Thailand. The defending champions will face either Iran or…
Author:  (@newsarea.bsky.social)
Author DID: did:plc:kqj4vuyjvmtnptvvdt2xijtk
Author Profile Image: https://cdn.bsky.app/img/avatar/plain/did:plc:kqj4vuyjvmtnptvvdt2xijtk/bafkreibcphjlsr2nmihau5fivfzxiawppid4bsq6lvlpc53x7qq4jfwlue
Author URL: https://bsky.app/profile/newsarea.bsky.social
Post URL: https://bsky.app/profile/newsarea.bsky.social/post/3mwehcdkjxd2n
Likes: 0
Reposts: 0
Replies: 0
Quotes: 0


Published Time: 2026-09-25T07:18:03Z
Post Text: Asian Games 2026 Day 6: Suruchi Singh and Kamaljeet Win Gold in Mixed 10m Air Pistol

25 September 2026 (Navroze Bureau)  India secured its second gold medal of the 2026 Asian Games as Suruchi Inder Singh and Kamaljeet won the mixed team 10m air pistol event in Aichi-Nagoya on Friday. The Indian…
Author:  (@navroze-india.bsky.social)
Author DID: did:plc:nndhrtds5t6ipm4zdvov6php
Author Profile Image: https://cdn.bsky.app/img/avatar/plain/did:plc:nndhrtds5t6ipm4zdvov6php/bafkreih3fj7z3xvpjtgousjaskqeebeahl4kncq3qtocpqcaiiz545dv2u
Author URL: https://bsky.app/profile/navroze-india.bsky.social
Post URL: https://bsky.app/profile/navroze-india.bsky.social/post/3mwda4a3psm22
Likes: 0
Reposts: 0
Replies: 0
Quotes: 0


Published Time: 2026-06-22T21:24:44.002Z
Post Text: 🗞️ Friday Finance #35 is live! This week: billionaires funding shows about themselves, the vague Iran deal, Colombia's cocaine boom, Guinness beating the odds & $30B in smuggled gold. A wild week in global finance 👇

fridayfinance.co/35th-edition/
Author: sam's friday finance weekly-ish (@fridayfinance.bsky.social)
Author DID: did:plc:mb3dgo74f2yssbnccjfh4g6z
Author Profile Image: https://cdn.bsky.app/img/avatar/plain/did:plc:mb3dgo74f2yssbnccjfh4g6z/bafkreib4hh4jb7d3dbvrpokgdiuwhxf5y544wgbjyoz7clahtlpgph2xze
Author URL: https://bsky.app/profile/fridayfinance.bsky.social
Post URL: https://bsky.app/profile/fridayfinance.bsky.social/post/3movt4qekrc2s
Likes: 0
Reposts: 0
Replies: 1
Quotes: 0


Published Time: 2025-10-23T14:57:32.319Z
Post Text: India are the first girls' champs in kabaddi's debut at the Asian Youth Games, and they've sealed the title after crushing Iran with an empathic 75-21 win in the gold final.

🥇 🇮🇳 India
🥈 🟩 Iran
🥉 🇹🇭 Thailand
🥉 🇧🇩 Bangladesh

#AYG2025   #WhereHeroesRise
Author: Archive (@archive041716.bsky.social)
Author DID: did:plc:de2ulpepjaul36mazt33vvdf
Author Profile Image: https://cdn.bsky.app/img/avatar/plain/did:plc:de2ulpepjaul36mazt33vvdf/bafkreicf76rblwo4h4z2abnh7b3qtrkd27bkmprlcw2t7ipxzm3gefgurm
Author URL: https://bsky.app/profile/archive041716.bsky.social
Post URL: https://bsky.app/profile/archive041716.bsky.social/post/3m3umnljyt626
Likes: 0
Reposts: 0
Replies: 0
Quotes: 0


Published Time: 2025-08-25T09:01:05.356020+00:00
Post Text: Feed: "Neptune Prime"
By: Maryam Sulaiman Abubakar on Monday, August 25, 2025
Author: Longtail News (@longtail-news.bsky.social)
Author DID: did:plc:o6ggjvnj4ze3mnrpnv5oravg
Author Profile Image: https://cdn.bsky.app/img/avatar/plain/did:plc:o6ggjvnj4ze3mnrpnv5oravg/bafkreidir7ju3jscr5rlwlg7r5raukdsizzszflwojh3pdm56cnem3k6hu
Author URL: https://bsky.app/profile/longtail-news.bsky.social
Post URL: https://bsky.app/profile/longtail-news.bsky.social/post/3lx7n7ugz6w2j
Likes: 0
Reposts: 0
Replies: 0
Quotes: 0


✅ Bluesky posts successfully saved to 'bluesky_posts.csv'

--- Bluesky DataFrame ---

,Published Time,Post Text,Author Name,Author Handle,Author DID,Author Profile Image,Author URL,Post URL,Likes,Reposts,Replies,Quotes
0,2026-09-26T17:10:25.000Z,,Mashable India [Unofficial],in.mashable.com.web.brid.gy,did:plc:tkzj743ruh5itf2pov2q5txv,https://cdn.bsky.app/img/avatar/plain/did:plc:...,https://bsky.app/profile/in.mashable.com.web.b...,https://bsky.app/profile/in.mashable.com.web.b...,0,0,0,0
1,2026-09-26T16:07:43Z,Asian Games 2026 Day 7: India win seven medals...,HFG INSIDER,health897.bsky.social,did:plc:euogifoh4mj52xvkbqcfqtti,https://cdn.bsky.app/img/avatar/plain/did:plc:...,https://bsky.app/profile/health897.bsky.social,https://bsky.app/profile/health897.bsky.social...,0,0,0,0
2,2026-09-26T10:55:45.726Z,India beat Iran to win ninth Gold medal in men...,,newsinc24.bsky.social,did:plc:6qomd7wrtbnrjq5p3cww7fuc,https://cdn.bsky.app/img/avatar/plain/did:plc:...,https://bsky.app/profile/newsinc24.bsky.social,https://bsky.app/profile/newsinc24.bsky.social...,0,0,0,0
3,2026-09-26T09:36:23.000Z,,Mashable India [Unofficial],in.mashable.com.web.brid.gy,did:plc:tkzj743ruh5itf2pov2q5txv,https://cdn.bsky.app/img/avatar/plain/did:plc:...,https://bsky.app/profile/in.mashable.com.web.b...,https://bsky.app/profile/in.mashable.com.web.b...,0,0,0,0
4,2026-09-25T18:59:24Z,Asian Games 2026 Kabaddi: India Storm Into Men...,,newsarea.bsky.social,did:plc:kqj4vuyjvmtnptvvdt2xijtk,https://cdn.bsky.app/img/avatar/plain/did:plc:...,https://bsky.app/profile/newsarea.bsky.social,https://bsky.app/profile/newsarea.bsky.social/...,0,0,0,0
5,2026-09-25T07:18:03Z,Asian Games 2026 Day 6: Suruchi Singh and Kama...,,navroze-india.bsky.social,did:plc:nndhrtds5t6ipm4zdvov6php,https://cdn.bsky.app/img/avatar/plain/did:plc:...,https://bsky.app/profile/navroze-india.bsky.so...,https://bsky.app/profile/navroze-india.bsky.so...,0,0,0,0
6,2026-06-22T21:24:44.002Z,🗞️ Friday Finance #35 is live! This week: bill...,sam's friday finance weekly-ish,fridayfinance.bsky.social,did:plc:mb3dgo74f2yssbnccjfh4g6z,https://cdn.bsky.app/img/avatar/plain/did:plc:...,https://bsky.app/profile/fridayfinance.bsky.so...,https://bsky.app/profile/fridayfinance.bsky.so...,0,0,1,0
7,2025-10-23T14:57:32.319Z,India are the first girls' champs in kabaddi's...,Archive,archive041716.bsky.social,did:plc:de2ulpepjaul36mazt33vvdf,https://cdn.bsky.app/img/avatar/plain/did:plc:...,https://bsky.app/profile/archive041716.bsky.so...,https://bsky.app/profile/archive041716.bsky.so...,0,0,0,0
8,2025-08-25T09:01:05.356020+00:00,"Feed: ""Neptune Prime""\nBy: Maryam Sulaiman Abu...",Longtail News,longtail-news.bsky.social,did:plc:o6ggjvnj4ze3mnrpnv5oravg,https://cdn.bsky.app/img/avatar/plain/did:plc:...,https://bsky.app/profile/longtail-news.bsky.so...,https://bsky.app/profile/longtail-news.bsky.so...,0,0,0,0

**Reddit API**

In [20]:
!pip install praw

Requirement already satisfied: praw in /usr/local/lib/python3.13/dist-packages (8.0.3)
Requirement already satisfied: defusedxml==0.7.1 in /usr/local/lib/python3.13/dist-packages (from praw) (0.7.1)
Requirement already satisfied: prawcore<5,>=4 in /usr/local/lib/python3.13/dist-packages (from praw) (4.0.0)
Requirement already satisfied: update-checker<2.0,>=1.0 in /usr/local/lib/python3.13/dist-packages (from praw) (1.0.0)
Requirement already satisfied: websocket-client<2,>=0.54.0 in /usr/local/lib/python3.13/dist-packages (from praw) (1.9.2)
Requirement already satisfied: requests<3.0,>=2.34.2 in /usr/local/lib/python3.13/dist-packages (from prawcore<5,>=4->praw) (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.34.2->prawcore<5,>=4->praw) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.34.2->prawcore<5,>=4->praw) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.34.2->prawcore<5,>=4->praw) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.34.2->prawcore<5,>=4->praw) (2026.7.22)

In [23]:
# Importing necessary libraries for Reddit API interaction
import praw
import datetime  # To format the timestamp from Reddit
import pandas as pd

# --- API Configuration ---
REDDIT_CLIENT_ID = 'utnSmiRRrv9ZDIlJ9LveMg'
REDDIT_CLIENT_SECRET = 'jzP9XRolmRsu3CNiDZmKF0IDDGcXpA'
REDDIT_USER_AGENT = 'python:moonsearcher:v1.0 (by /u/Dependent_Car_5879)'

# --- Search Parameters ---
try:
    question = " ".join(news_check).strip()
    num_results = 100  # Automatically take up to 100 results
except EOFError:
    print("\nNo input provided for search query. Exiting.")
    exit()

# --- Main Execution Block ---
if not REDDIT_CLIENT_ID or not REDDIT_CLIENT_SECRET or not question:
    print("ERROR: Client ID, Client Secret, and a search query are required.")
else:
    try:
        reddit = praw.Reddit(
            client_id=REDDIT_CLIENT_ID,
            client_secret=REDDIT_CLIENT_SECRET,
            user_agent=REDDIT_USER_AGENT,
        )

        search_results = reddit.subreddit("all").search(
            query=question,
            sort='new',
            limit=num_results
        )

        submissions = list(search_results)

        if not submissions:
            print("\nNo recent posts found for that query.")
        else:
            print(f"\n--- Found {len(submissions)} Posts ---\n")


            reddit_rows = []

            for submission in submissions:
                author_name = submission.author.name if submission.author else "[deleted]"
                post_url = f"https://www.reddit.com{submission.permalink}"
                author_url = f"https://www.reddit.com/user/{author_name}" if author_name != "[deleted]" else "N/A"
                published_time = datetime.datetime.fromtimestamp(submission.created_utc)


                print(f"Published Time: {published_time.strftime('%Y-%m-%d %H:%M:%S')}")
                print(f"Post Title: {submission.title}")
                print(f"Subreddit: r/{submission.subreddit.display_name}")
                print(f"Score: {submission.score} (Upvote Ratio: {submission.upvote_ratio * 100:.0f}%)")
                print(f"Author: u/{author_name}")
                print(f"Author URL: {author_url}")
                print(f"Post URL: {post_url}")

                post_text = submission.selftext.replace(chr(10), ' ') if submission.selftext else None


                image_url = None
                if submission.url.endswith(('.jpg', '.jpeg', '.png', '.gif')):
                    image_url = submission.url
                elif hasattr(submission, 'preview'):
                    try:
                        image_url = submission.preview['images'][0]['source']['url']
                    except (KeyError, IndexError):
                        pass

                if image_url:
                    print(f"Image URL: {image_url}")
                else:
                    print("Image: None")

                print("\n" + "-" * 60 + "\n")

                reddit_rows.append({
                    "Published Time": published_time.strftime('%Y-%m-%d %H:%M:%S'),
                    "Post Title": submission.title,
                    "Subreddit": submission.subreddit.display_name,
                    "Score": submission.score,
                    "Upvote Ratio (%)": f"{submission.upvote_ratio * 100:.0f}",
                    "Author": author_name,
                    "Author URL": author_url,
                    "Post URL": post_url,
                    "Post Text": post_text,
                    "Image URL": image_url
                })


            df_reddit = pd.DataFrame(reddit_rows)
            df_reddit.to_csv('reddit.csv', index=False, encoding='utf-8')

            print("✅ Reddit posts successfully saved to 'reddit.csv'")

    except praw.exceptions.PRAWException as e:
        print("\n--- API ERROR ---")
        print("An error occurred with the Reddit API. This could be due to invalid credentials or a connection problem.")
        print(f"Error details: {e}")
    except Exception as e:
        print(f"\nAn unexpected error occurred.")
        print(f"Error details: {e}")

        # --- Display DataFrame ---
    print("\n--- Reddit DataFrame ---\n")
    display(df_reddit)

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

--- Found 100 Posts ---

Published Time: 2026-09-28 07:58:05
Post Title: 📊 NordFX: Quarter-End Test - JOLTS, PCE, USD and Gold Into the Q3 Close
Subreddit: r/NordFX
Score: 1 (Upvote Ratio: 100%)
Author: u/Marketing_NordFX
Author URL: https://www.reddit.com/user/Marketing_NordFX
Post URL: https://www.reddit.com/r/NordFX/comments/1ws8i61/nordfx_quarterend_test_jolts_pce_usd_and_gold/
Image URL: https://external-preview.redd.it/ODNnbmoweGV3N3NoMTHlsiULYxYa5l1ejbAt3UwD4WA1z-qfgpIhryOGRvXi.png?format=pjpg&auto=webp&s=bf029dd0710999b3e53ea16819a1ab27a2d9dc23

------------------------------------------------------------

Published Time: 2026-09-28 07:50:40
Post Title: After using a GTX 1060 mobile since it came I finally got an RTX5070 PC. I played everything though.
Subreddit: r/gamesuggestions
Score: 2 (Upvote Ratio: 100%)
Author: u/AtmosphereBlue
Author URL: https://www.reddit.com/user/AtmosphereBlue
Post URL: https://www.reddit.com/r/gamesuggestions/comments/1ws8e56/after_using_a_gtx_1060_mobile_since_it_came_i/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 07:46:39
Post Title: [Business] - Gold price prediction: What are the factors that will drive gold this week? | Times of India
Subreddit: r/MetalsOnReddit
Score: 1 (Upvote Ratio: 100%)
Author: u/Then_Marionberry_259
Author URL: https://www.reddit.com/user/Then_Marionberry_259
Post URL: https://www.reddit.com/r/MetalsOnReddit/comments/1ws8bxq/business_gold_price_prediction_what_are_the/
Image URL: https://external-preview.redd.it/iHSGbIRF4mQhBcaAe5wM22o2HSbefyvdYlT-jboV-gk.jpeg?auto=webp&s=b991cafac9385551f6ea322644900180a628d782

------------------------------------------------------------

Published Time: 2026-09-28 07:44:10
Post Title: Mahanirvana Tantra Chapter 9 Part 6
Subreddit: r/TantraMarg
Score: 2 (Upvote Ratio: 100%)
Author: u/Straight-Cable433
Author URL: https://www.reddit.com/user/Straight-Cable433
Post URL: https://www.reddit.com/r/TantraMarg/comments/1ws8ai5/mahanirvana_tantra_chapter_9_part_6/
Image URL: https://i.redd.it/um9qciiyt7sh1.jpeg

------------------------------------------------------------

Published Time: 2026-09-28 07:37:21
Post Title: Got scammed by Zevana - “India’s most trusted destination for gold-plated jewellery”
Subreddit: r/indianbeautyyappers
Score: 2 (Upvote Ratio: 100%)
Author: u/Effective_Lawyer_647
Author URL: https://www.reddit.com/user/Effective_Lawyer_647
Post URL: https://www.reddit.com/r/indianbeautyyappers/comments/1ws86np/got_scammed_by_zevana_indias_most_trusted/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 07:31:17
Post Title: Lost money to Zevana- “India’s most trusted destination for gold plated jewellery”
Subreddit: r/IsThisAScamIndia
Score: 1 (Upvote Ratio: 100%)
Author: u/Effective_Lawyer_647
Author URL: https://www.reddit.com/user/Effective_Lawyer_647
Post URL: https://www.reddit.com/r/IsThisAScamIndia/comments/1ws838y/lost_money_to_zevana_indias_most_trusted/

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Image: None

------------------------------------------------------------

Published Time: 2026-09-28 07:31:05
Post Title: This is why I can't get a better winrate on Mathilda... Mid lane is the most toxic role by far.
Subreddit: r/MobileLegendsGame
Score: 1 (Upvote Ratio: 100%)
Author: u/Dependent_Wafer3866
Author URL: https://www.reddit.com/user/Dependent_Wafer3866
Post URL: https://www.reddit.com/r/MobileLegendsGame/comments/1ws834g/this_is_why_i_cant_get_a_better_winrate_on/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 07:26:56
Post Title: 📊 12:00 PM GIFT NIFTY Update
Subreddit: r/GIFTNiftyLive
Score: 1 (Upvote Ratio: 100%)
Author: u/giftniftylive
Author URL: https://www.reddit.com/user/giftniftylive
Post URL: https://www.reddit.com/r/GIFTNiftyLive/comments/1ws80th/1200_pm_gift_nifty_update/
Image URL: https://i.redd.it/j2p649ysq7sh1.jpeg

------------------------------------------------------------

Published Time: 2026-09-28 07:22:02
Post Title: Captain Mukhtiar Singh — The Forgotten Jat Wrestling Legend
Subreddit: r/UNITEDJATFRONT
Score: 10 (Upvote Ratio: 92%)
Author: u/Ancient_Emphasis_709
Author URL: https://www.reddit.com/user/Ancient_Emphasis_709
Post URL: https://www.reddit.com/r/UNITEDJATFRONT/comments/1ws7y57/captain_mukhtiar_singh_the_forgotten_jat/
Image URL: https://i.redd.it/nuttxp50q7sh1.jpeg

------------------------------------------------------------

Published Time: 2026-09-28 07:21:38
Post Title: Mirabai Chanu Wins Gold at Asian Games !
Subreddit: r/Feminism4India
Score: 5 (Upvote Ratio: 100%)
Author: u/Amn_BA
Author URL: https://www.reddit.com/user/Amn_BA
Post URL: https://www.reddit.com/r/Feminism4India/comments/1ws7xxn/mirabai_chanu_wins_gold_at_asian_games/
Image URL: https://i.redd.it/ppipklrxp7sh1.png

------------------------------------------------------------

Published Time: 2026-09-28 07:21:13
Post Title: Suggestions for portfolio
Subreddit: r/MutualfundsIndia
Score: 2 (Upvote Ratio: 100%)
Author: u/AvocadoBright7940
Author URL: https://www.reddit.com/user/AvocadoBright7940
Post URL: https://www.reddit.com/r/MutualfundsIndia/comments/1ws7xpk/suggestions_for_portfolio/

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Image: None

------------------------------------------------------------

Published Time: 2026-09-28 07:18:26
Post Title: Mutual fund sip suggestions
Subreddit: r/IndianMutualFunds
Score: 3 (Upvote Ratio: 100%)
Author: u/AvocadoBright7940
Author URL: https://www.reddit.com/user/AvocadoBright7940
Post URL: https://www.reddit.com/r/IndianMutualFunds/comments/1ws7w4m/mutual_fund_sip_suggestions/
Image URL: https://i.redd.it/1vj6peycp7sh1.jpeg

------------------------------------------------------------

Published Time: 2026-09-28 07:18:02
Post Title: Slovak news article focused on Misha at Nepela Memorial
Subreddit: r/MikhailShaidorov
Score: 7 (Upvote Ratio: 100%)
Author: u/Due_Employment_530
Author URL: https://www.reddit.com/user/Due_Employment_530
Post URL: https://www.reddit.com/r/MikhailShaidorov/comments/1ws7vvy/slovak_news_article_focused_on_misha_at_nepela/
Image URL: https://i.redd.it/m7ungx77p7sh1.png

------------------------------------------------------------

Published Time: 2026-09-28 07:10:26
Post Title: Asia Market Quick Take – 28 September, 2026
Subreddit: r/GeopoliticsMicroscope
Score: 1 (Upvote Ratio: 100%)
Author: u/CupEcstatic2721
Author URL: https://www.reddit.com/user/CupEcstatic2721
Post URL: https://www.reddit.com/r/GeopoliticsMicroscope/comments/1ws7rcp/asia_market_quick_take_28_september_2026/
Image URL: https://external-preview.redd.it/UeV-AuE304Ci7eBB7fPfbYmw1XiI7p0T2YB_ZQWDVg8.jpeg?auto=webp&s=81bbe3d40957f50fccf6d335a4a8763abfd91706

------------------------------------------------------------

Published Time: 2026-09-28 07:03:50
Post Title: [Business] - Gold price prediction: What are the factors that will drive gold this week? | Times of India
Subreddit: r/AutoNewspaper
Score: 1 (Upvote Ratio: 100%)
Author: u/AutoNewspaperAdmin
Author URL: https://www.reddit.com/user/AutoNewspaperAdmin
Post URL: https://www.reddit.com/r/AutoNewspaper/comments/1ws7ndu/business_gold_price_prediction_what_are_the/
Image URL: https://external-preview.redd.it/iHSGbIRF4mQhBcaAe5wM22o2HSbefyvdYlT-jboV-gk.jpeg?auto=webp&s=b991cafac9385551f6ea322644900180a628d782

------------------------------------------------------------

Published Time: 2026-09-28 07:03:17
Post Title: The Hardest India Challange
Subreddit: r/SolarNations2
Score: 6 (Upvote Ratio: 100%)
Author: u/magniciv
Author URL: https://www.reddit.com/user/magniciv
Post URL: https://www.reddit.com/r/SolarNations2/comments/1ws7n3k/the_hardest_india_challange/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 07:02:59
Post Title: 2026 Nagoya Asian Games - Athletics Day 6 Discussion Thread
Subreddit: r/trackandfield
Score: 1 (Upvote Ratio: 100%)
Author: u/AutoModerator
Author URL: https://www.reddit.com/user/AutoModerator
Post URL: https://www.reddit.com/r/trackandfield/comments/1ws7mxb/2026_nagoya_asian_games_athletics_day_6/
Image URL: https://external-preview.redd.it/sYr4JJXvlO4ueMIoTPuRfdAHgRIo9bUOO9JC1VjonTM.png?auto=webp&s=295fc82b4cabd73f177aae53f5be7fe96e904b13

------------------------------------------------------------

Published Time: 2026-09-28 06:58:12
Post Title: WTS Longines Presence Automatic [timestamp-yes][Price-98,500]
Subreddit: r/WatchesIndiaExchange
Score: 3 (Upvote Ratio: 100%)
Author: u/CacheronVonstantin
Author URL: https://www.reddit.com/user/CacheronVonstantin
Post URL: https://www.reddit.com/r/WatchesIndiaExchange/comments/1ws7jq5/wts_longines_presence_automatic/

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Image: None

------------------------------------------------------------

Published Time: 2026-09-28 06:58:06
Post Title: Kashi tu hai Avinashi.. har har mahadev 🔱.. Jyotirlinga, Varanasi 🕉️
Subreddit: r/IndianFestivals
Score: 23 (Upvote Ratio: 100%)
Author: u/AssetsSutram
Author URL: https://www.reddit.com/user/AssetsSutram
Post URL: https://www.reddit.com/r/IndianFestivals/comments/1ws7jnu/kashi_tu_hai_avinashi_har_har_mahadev_jyotirlinga/
Image URL: https://i.redd.it/f54j1icql7sh1.png

------------------------------------------------------------

Published Time: 2026-09-28 06:56:05
Post Title: WTS Longines Presence Automatic [Timestamp-yes] [Price - Yes]
Subreddit: r/WatchEnthusiastIndia
Score: 4 (Upvote Ratio: 100%)
Author: u/CacheronVonstantin
Author URL: https://www.reddit.com/user/CacheronVonstantin
Post URL: https://www.reddit.com/r/WatchEnthusiastIndia/comments/1ws7ig5/wts_longines_presence_automatic_timestampyes/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 06:55:46
Post Title: काशी तू है अविनाशी .. हर हर महादेव 🔱.. Kashi Vishwanath temple, Varanasi 🕉️
Subreddit: r/BharatMandir
Score: 1 (Upvote Ratio: 100%)
Author: u/AssetsSutram
Author URL: https://www.reddit.com/user/AssetsSutram
Post URL: https://www.reddit.com/r/BharatMandir/comments/1ws7i9v/कश_त_ह_अवनश_हर_हर_महदव_kashi_vishwanath_temple/
Image URL: https://i.redd.it/9gd2nawal7sh1.png

------------------------------------------------------------

Published Time: 2026-09-28 06:50:26
Post Title: What are the world's biggest space powers?
Subreddit: r/MapBasedPolls
Score: 1 (Upvote Ratio: 67%)
Author: u/CartographerOwn8143
Author URL: https://www.reddit.com/user/CartographerOwn8143
Post URL: https://www.reddit.com/r/MapBasedPolls/comments/1ws7f4y/what_are_the_worlds_biggest_space_powers/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 06:43:29
Post Title: RAFFLE | Locust wings for 12GB
Subreddit: r/lioden
Score: 2 (Upvote Ratio: 100%)
Author: u/kuyaqrel
Author URL: https://www.reddit.com/user/kuyaqrel
Post URL: https://www.reddit.com/r/lioden/comments/1ws7aye/raffle_locust_wings_for_12gb/
Image URL: https://i.redd.it/hl7m8au4j7sh1.jpeg

------------------------------------------------------------

Published Time: 2026-09-28 06:37:47
Post Title: How to get better at learning TFT - Advanced points.
Subreddit: r/CompetitiveTFT
Score: 25 (Upvote Ratio: 89%)
Author: u/Demacian_Raptor
Author URL: https://www.reddit.com/user/Demacian_Raptor
Post URL: https://www.reddit.com/r/CompetitiveTFT/comments/1ws77l6/how_to_get_better_at_learning_tft_advanced_points/

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Image: None

------------------------------------------------------------

Published Time: 2026-09-28 06:35:43
Post Title: Who to reach out for NZXT power supply warmly claims?
Subreddit: r/IndianGaming
Score: 1 (Upvote Ratio: 100%)
Author: u/ZamnBoii
Author URL: https://www.reddit.com/user/ZamnBoii
Post URL: https://www.reddit.com/r/IndianGaming/comments/1ws76d0/who_to_reach_out_for_nzxt_power_supply_warmly/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 06:29:51
Post Title: UFL GAME – SEPTEMBER 2026 SUMMARY
Subreddit: r/UFLTheGame
Score: 3 (Upvote Ratio: 100%)
Author: u/ArekT5
Author URL: https://www.reddit.com/user/ArekT5
Post URL: https://www.reddit.com/r/UFLTheGame/comments/1ws72vb/ufl_game_september_2026_summary/

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Image: None

------------------------------------------------------------

Published Time: 2026-09-28 06:26:01
Post Title: Who in your opinion are the King and Queen of the 4 Great Racecourses?
Subreddit: r/HorseRacingJP
Score: 13 (Upvote Ratio: 100%)
Author: u/Working-Chip1318
Author URL: https://www.reddit.com/user/Working-Chip1318
Post URL: https://www.reddit.com/r/HorseRacingJP/comments/1ws70k7/who_in_your_opinion_are_the_king_and_queen_of_the/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 06:25:46
Post Title: HeadHunter update: you can now post your own bounties
Subreddit: r/classicwowplus
Score: 12 (Upvote Ratio: 81%)
Author: u/HeadHunterWoW
Author URL: https://www.reddit.com/user/HeadHunterWoW
Post URL: https://www.reddit.com/r/classicwowplus/comments/1ws70ep/headhunter_update_you_can_now_post_your_own/
Image URL: https://external-preview.redd.it/avr6d2xwf7sh1.png?auto=webp&s=813394bf97df7a376dc4c9efea3b9fc02fd84b16

------------------------------------------------------------

Published Time: 2026-09-28 06:20:34
Post Title: Back to the basics.
Subreddit: r/PlayTheBazaar
Score: 9 (Upvote Ratio: 85%)
Author: u/Scared-Tear4142
Author URL: https://www.reddit.com/user/Scared-Tear4142
Post URL: https://www.reddit.com/r/PlayTheBazaar/comments/1ws6xb1/back_to_the_basics/
Image URL: https://i.redd.it/f1na15o1f7sh1.jpeg

------------------------------------------------------------

Published Time: 2026-09-28 06:16:44
Post Title: [Business] - Gold price crash today: Why is MCX Gold down over 2% & what should you do? Explained | Times of India
Subreddit: r/MetalsOnReddit
Score: 1 (Upvote Ratio: 100%)
Author: u/Then_Marionberry_259
Author URL: https://www.reddit.com/user/Then_Marionberry_259
Post URL: https://www.reddit.com/r/MetalsOnReddit/comments/1ws6v01/business_gold_price_crash_today_why_is_mcx_gold/
Image URL: https://external-preview.redd.it/PoKx2kKIpHH7-jm6bOw5W3J8-ClKBCyPUDF-P_m7ltQ.jpeg?auto=webp&s=87d894bfd29dd6a54d4128a23502fc76df72d8a9

------------------------------------------------------------

Published Time: 2026-09-28 06:12:24
Post Title: Viking - Ocean, River, and Expedition Cruises!
Subreddit: r/u_YourPremierTravels
Score: 1 (Upvote Ratio: 100%)
Author: u/YourPremierTravels
Author URL: https://www.reddit.com/user/YourPremierTravels
Post URL: https://www.reddit.com/r/u_YourPremierTravels/comments/1ws6sdb/viking_ocean_river_and_expedition_cruises/
Image URL: https://i.redd.it/cij0t1b8d7sh1.jpeg

------------------------------------------------------------

Published Time: 2026-09-28 06:10:04
Post Title: The 2018 U16 Olympiad that launched the Uzbek Chess Dynasty
Subreddit: r/chess
Score: 92 (Upvote Ratio: 94%)
Author: u/ghostmaster93
Author URL: https://www.reddit.com/user/ghostmaster93
Post URL: https://www.reddit.com/r/chess/comments/1ws6qy2/the_2018_u16_olympiad_that_launched_the_uzbek/
Image URL: https://i.redd.it/fm90oi7ha7sh1.jpeg

------------------------------------------------------------

Published Time: 2026-09-28 06:09:32
Post Title: What's wrong in gold?
Subreddit: r/IndiaStocks
Score: 3 (Upvote Ratio: 100%)
Author: u/DisasterCrafty4361
Author URL: https://www.reddit.com/user/DisasterCrafty4361
Post URL: https://www.reddit.com/r/IndiaStocks/comments/1ws6qmc/whats_wrong_in_gold/
Image URL: https://i.redd.it/v3o0vlp2d7sh1.jpeg

------------------------------------------------------------

Published Time: 2026-09-28 06:06:22
Post Title: So apparently the swan is stupidly broken
Subreddit: r/PlayTheBazaar
Score: 1 (Upvote Ratio: 100%)
Author: u/RandyRenegade
Author URL: https://www.reddit.com/user/RandyRenegade
Post URL: https://www.reddit.com/r/PlayTheBazaar/comments/1ws6oow/so_apparently_the_swan_is_stupidly_broken/
Image URL: https://i.redd.it/0vioid4ic7sh1.png

------------------------------------------------------------

Published Time: 2026-09-28 05:58:26
Post Title: [Business] - Gold price crash today: Why is MCX Gold down over 2% & what should you do? Explained | Times of India
Subreddit: r/AutoNewspaper
Score: 1 (Upvote Ratio: 100%)
Author: u/AutoNewspaperAdmin
Author URL: https://www.reddit.com/user/AutoNewspaperAdmin
Post URL: https://www.reddit.com/r/AutoNewspaper/comments/1ws6jp6/business_gold_price_crash_today_why_is_mcx_gold/
Image URL: https://external-preview.redd.it/PoKx2kKIpHH7-jm6bOw5W3J8-ClKBCyPUDF-P_m7ltQ.jpeg?auto=webp&s=87d894bfd29dd6a54d4128a23502fc76df72d8a9

------------------------------------------------------------

Published Time: 2026-09-28 05:46:53
Post Title: [IN] - Tamil Nadu CM Vijay to launch one-gram gold ring scheme for newborns today | Times of India
Subreddit: r/MetalsOnReddit
Score: 1 (Upvote Ratio: 100%)
Author: u/Then_Marionberry_259
Author URL: https://www.reddit.com/user/Then_Marionberry_259
Post URL: https://www.reddit.com/r/MetalsOnReddit/comments/1ws6chp/in_tamil_nadu_cm_vijay_to_launch_onegram_gold/
Image URL: https://external-preview.redd.it/8Wj5kHrnhp7jIs60vQ99rMZuJC0B1n7OPFYSemvwIRA.png?auto=webp&s=ca8f4ede7f0b6107a3feda08d9cc027e849b858a

------------------------------------------------------------

Published Time: 2026-09-28 05:30:25
Post Title: Rhetorical Questions to Our Chief Criminal Commander Thief
Subreddit: r/PoetryWritingClub
Score: 1 (Upvote Ratio: 100%)
Author: u/Wooden-Frame-3740
Author URL: https://www.reddit.com/user/Wooden-Frame-3740
Post URL: https://www.reddit.com/r/PoetryWritingClub/comments/1ws626x/rhetorical_questions_to_our_chief_criminal/

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Image: None

------------------------------------------------------------

Published Time: 2026-09-28 05:23:57
Post Title: Selling India vs Brazil - 4 Gold tickets, Oct 3, Kolkata - at 5K flat
Subreddit: r/IndiaInHindi
Score: 1 (Upvote Ratio: 100%)
Author: u/Adventurous-Lemon459
Author URL: https://www.reddit.com/user/Adventurous-Lemon459
Post URL: https://www.reddit.com/r/IndiaInHindi/comments/1ws5y8w/selling_india_vs_brazil_4_gold_tickets_oct_3/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 05:23:09
Post Title: [IN] - Tamil Nadu CM Vijay to launch one-gram gold ring scheme for newborns today | Times of India
Subreddit: r/AutoNewspaper
Score: 1 (Upvote Ratio: 100%)
Author: u/AutoNewspaperAdmin
Author URL: https://www.reddit.com/user/AutoNewspaperAdmin
Post URL: https://www.reddit.com/r/AutoNewspaper/comments/1ws5xqk/in_tamil_nadu_cm_vijay_to_launch_onegram_gold/
Image URL: https://external-preview.redd.it/8Wj5kHrnhp7jIs60vQ99rMZuJC0B1n7OPFYSemvwIRA.png?auto=webp&s=ca8f4ede7f0b6107a3feda08d9cc027e849b858a

------------------------------------------------------------

Published Time: 2026-09-28 05:21:42
Post Title: Selling India vs Brazil - 4 Gold tickets, Oct 3, Kolkata - at 5K flat
Subreddit: r/ConcertsIndia_
Score: 1 (Upvote Ratio: 100%)
Author: u/Adventurous-Lemon459
Author URL: https://www.reddit.com/user/Adventurous-Lemon459
Post URL: https://www.reddit.com/r/ConcertsIndia_/comments/1ws5wtp/selling_india_vs_brazil_4_gold_tickets_oct_3/

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Image: None

------------------------------------------------------------

Published Time: 2026-09-28 05:20:51
Post Title: Selling India vs Brazil - 4 Gold tickets, Oct 3, Kolkata - at 5K flat
Subreddit: r/ticketresellingindia
Score: 1 (Upvote Ratio: 100%)
Author: u/Adventurous-Lemon459
Author URL: https://www.reddit.com/user/Adventurous-Lemon459
Post URL: https://www.reddit.com/r/ticketresellingindia/comments/1ws5wae/selling_india_vs_brazil_4_gold_tickets_oct_3/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 05:20:25
Post Title: Selling India vs Brazil - 4 Gold tickets, Oct 3, Kolkata - at 5K flat
Subreddit: r/Tickets
Score: 1 (Upvote Ratio: 100%)
Author: u/Adventurous-Lemon459
Author URL: https://www.reddit.com/user/Adventurous-Lemon459
Post URL: https://www.reddit.com/r/Tickets/comments/1ws5vzi/selling_india_vs_brazil_4_gold_tickets_oct_3/

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Image: None

------------------------------------------------------------

Published Time: 2026-09-28 05:16:13
Post Title: I am hard stuck at Gold I gate, please help me.
Subreddit: r/MergeTacticsSC
Score: 2 (Upvote Ratio: 75%)
Author: u/Overall-Candidate884
Author URL: https://www.reddit.com/user/Overall-Candidate884
Post URL: https://www.reddit.com/r/MergeTacticsSC/comments/1ws5tbl/i_am_hard_stuck_at_gold_i_gate_please_help_me/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 05:15:33
Post Title: Rental Car Broker vs Direct Booking: What's Better in 2026-2027?
Subreddit: r/u_RentCarForYou_Travel
Score: 1 (Upvote Ratio: 100%)
Author: u/RentCarForYou_Travel
Author URL: https://www.reddit.com/user/RentCarForYou_Travel
Post URL: https://www.reddit.com/r/u_RentCarForYou_Travel/comments/1ws5swn/rental_car_broker_vs_direct_booking_whats_better/
Image URL: https://i.redd.it/jt633drf37sh1.png

------------------------------------------------------------

Published Time: 2026-09-28 05:09:09
Post Title: I'm surprised nobody has talked about 11'09"01 September 11 yet
Subreddit: r/TrueFilm
Score: 0 (Upvote Ratio: 23%)
Author: u/Micro_Pinny_360
Author URL: https://www.reddit.com/user/Micro_Pinny_360
Post URL: https://www.reddit.com/r/TrueFilm/comments/1ws5oua/im_surprised_nobody_has_talked_about_110901/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 05:04:05
Post Title: 28 September 2026
Subreddit: r/dailygeopolitik
Score: 1 (Upvote Ratio: 100%)
Author: u/Sweet_Collection3041
Author URL: https://www.reddit.com/user/Sweet_Collection3041
Post URL: https://www.reddit.com/r/dailygeopolitik/comments/1ws5lpp/28_september_2026/
Image URL: https://external-preview.redd.it/QT-r6ez4FngjbqjAdDG0zvHXfCV9xQuqfWzmD1cLDZw.jpeg?auto=webp&s=80b77ff9415d680019c970e867d52497b5e73f46

------------------------------------------------------------

Published Time: 2026-09-28 05:03:36
Post Title: India wins its 2nd consecutive men’s Kabaddi gold at the Asian Games, defeating Iran in a thrilling final to claim the country’s 9th gold medal in the event 🥇
Subreddit: r/incredible_indians
Score: 107 (Upvote Ratio: 99%)
Author: u/Unusual_Wrap_8325
Author URL: https://www.reddit.com/user/Unusual_Wrap_8325
Post URL: https://www.reddit.com/r/incredible_indians/comments/1ws5ldf/india_wins_its_2nd_consecutive_mens_kabaddi_gold/
Image URL: https://external-preview.redd.it/ZWVmYzIwMDgxN3NoMSeu1usPEitRTD3_ku-uX3G-To4n1e_aMkMI_q7l6DXD.png?format=pjpg&auto=webp&s=7a54c47d997d6b66f60ca7b1e60f32617225e848

------------------------------------------------------------

Published Time: 2026-09-28 05:01:43
Post Title: Marine Electricals getting into flow lately. Anyone tracking this for a swing?
Subreddit: r/IndianStockMarket
Score: 1 (Upvote Ratio: 67%)
Author: u/ripradaman
Author URL: https://www.reddit.com/user/ripradaman
Post URL: https://www.reddit.com/r/IndianStockMarket/comments/1ws5k41/marine_electricals_getting_into_flow_lately/

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Image: None

------------------------------------------------------------

Published Time: 2026-09-28 05:01:28
Post Title: NordFX Morning Update – September 28, 2026
Subreddit: r/NordFX
Score: 1 (Upvote Ratio: 100%)
Author: u/Marketing_NordFX
Author URL: https://www.reddit.com/user/Marketing_NordFX
Post URL: https://www.reddit.com/r/NordFX/comments/1ws5jxr/nordfx_morning_update_september_28_2026/
Image URL: https://i.redd.it/osy64bgx07sh1.png

------------------------------------------------------------

Published Time: 2026-09-28 05:00:37
Post Title: There will be Billions of AI personal assistants in 5 years.  The Agent Wars have begun: Muse vs Instinct vs Claude Cowork vs Grok Bot vs ChatGPT Work vs OpenClaw vs Hermes vs Siri AI, compared on price, power and  25 use cases you can try.
Subreddit: r/CMO_Huddles
Score: 2 (Upvote Ratio: 100%)
Author: u/Beginning-Willow-801
Author URL: https://www.reddit.com/user/Beginning-Willow-801
Post URL: https://www.reddit.com/r/CMO_Huddles/comments/1ws5jal/there_will_be_billions_of_ai_personal_assistants/
Image URL: https://i.redd.it/nuy9phih07sh1.png

------------------------------------------------------------

Published Time: 2026-09-28 05:00:25
Post Title: There will be Billions of AI personal assistants in 5 years.  The Agent Wars have begun: Muse vs Instinct vs Claude Cowork vs Grok Bot vs ChatGPT Work vs OpenClaw vs Hermes vs Siri AI, compared on price, power and  25 use cases you can try.
Subreddit: r/ThinkingDeeplyAI
Score: 2 (Upvote Ratio: 100%)
Author: u/Beginning-Willow-801
Author URL: https://www.reddit.com/user/Beginning-Willow-801
Post URL: https://www.reddit.com/r/ThinkingDeeplyAI/comments/1ws5j55/there_will_be_billions_of_ai_personal_assistants/
Image URL: https://i.redd.it/bi7ygkja07sh1.png

------------------------------------------------------------

Published Time: 2026-09-28 04:59:12
Post Title: There will be Billions of AI personal assistants in 5 years.  The Agent Wars have begun: Muse vs Instinct vs Claude Cowork vs Grok Bot vs ChatGPT Work vs OpenClaw vs Hermes vs Siri AI, compared on price, power and  25 use cases you can try.
Subreddit: r/promptingmagic
Score: 3 (Upvote Ratio: 100%)
Author: u/Beginning-Willow-801
Author URL: https://www.reddit.com/user/Beginning-Willow-801
Post URL: https://www.reddit.com/r/promptingmagic/comments/1ws5ibr/there_will_be_billions_of_ai_personal_assistants/
Image URL: https://i.redd.it/9b4jg3a407sh1.png

------------------------------------------------------------

Published Time: 2026-09-28 04:53:41
Post Title: 🤎 Meet Carmelle Collado!
Subreddit: r/CarmelleCollado
Score: 1 (Upvote Ratio: 100%)
Author: u/Awkward_Good_2409
Author URL: https://www.reddit.com/user/Awkward_Good_2409
Post URL: https://www.reddit.com/r/CarmelleCollado/comments/1ws5esm/meet_carmelle_collado/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 04:51:04
Post Title: What does this mean
Subreddit: r/balatro
Score: 3 (Upvote Ratio: 100%)
Author: u/quickturtle27
Author URL: https://www.reddit.com/user/quickturtle27
Post URL: https://www.reddit.com/r/balatro/comments/1ws5d3y/what_does_this_mean/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 04:49:31
Post Title: Proud to present my dumbest black deck gold stake win
Subreddit: r/balatro
Score: 1 (Upvote Ratio: 100%)
Author: u/Enough-Map1162
Author URL: https://www.reddit.com/user/Enough-Map1162
Post URL: https://www.reddit.com/r/balatro/comments/1ws5c49/proud_to_present_my_dumbest_black_deck_gold_stake/

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Image: None

------------------------------------------------------------

Published Time: 2026-09-28 04:46:45
Post Title: [Business] - Gold, Silver rate today live updates: Gold drops more than 2% as oil surge boosts US rate hike bets | Times of India
Subreddit: r/MetalsOnReddit
Score: 1 (Upvote Ratio: 100%)
Author: u/Then_Marionberry_259
Author URL: https://www.reddit.com/user/Then_Marionberry_259
Post URL: https://www.reddit.com/r/MetalsOnReddit/comments/1ws5adv/business_gold_silver_rate_today_live_updates_gold/
Image URL: https://external-preview.redd.it/2mLprpd6MSdYfXeQiyUqs44v5fxi0kFRPvgQ2bfptfA.jpeg?auto=webp&s=bfbb608de19dafc533dcd5f263d359297a64e425

------------------------------------------------------------

Published Time: 2026-09-28 04:38:31
Post Title: Autumn Perfume Bingo Challenge
Subreddit: r/indieperfumeandmore
Score: 2 (Upvote Ratio: 100%)
Author: u/LadyAntiope
Author URL: https://www.reddit.com/user/LadyAntiope
Post URL: https://www.reddit.com/r/indieperfumeandmore/comments/1ws5557/autumn_perfume_bingo_challenge/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 04:36:53
Post Title: Got this buddy on free spin is it luck or common
Subreddit: r/BGMI
Score: 1 (Upvote Ratio: 56%)
Author: u/damnsasuke
Author URL: https://www.reddit.com/user/damnsasuke
Post URL: https://www.reddit.com/r/BGMI/comments/1ws544v/got_this_buddy_on_free_spin_is_it_luck_or_common/
Image URL: https://i.redd.it/7kc24ukjw6sh1.jpeg

------------------------------------------------------------

Published Time: 2026-09-28 04:32:45
Post Title: Anyone up for barter
Subreddit: r/IndianReaders
Score: 2 (Upvote Ratio: 100%)
Author: u/Immediate_Break8353
Author URL: https://www.reddit.com/user/Immediate_Break8353
Post URL: https://www.reddit.com/r/IndianReaders/comments/1ws51fd/anyone_up_for_barter/
Image URL: https://i.redd.it/nanueuysv6sh1.jpeg

------------------------------------------------------------

Published Time: 2026-09-28 04:31:46
Post Title: [Street Fighter] How inefficient is M. Bison’s plan?
Subreddit: r/Fighters
Score: 0 (Upvote Ratio: 50%)
Author: u/Mountain-Magician294
Author URL: https://www.reddit.com/user/Mountain-Magician294
Post URL: https://www.reddit.com/r/Fighters/comments/1ws50tl/street_fighter_how_inefficient_is_m_bisons_plan/

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Image: None

------------------------------------------------------------

Published Time: 2026-09-28 04:29:55
Post Title: News Headlines 28 Sept 2026
Subreddit: r/upsc_discussions
Score: 2 (Upvote Ratio: 100%)
Author: u/VIDYA_KOZHIKODE
Author URL: https://www.reddit.com/user/VIDYA_KOZHIKODE
Post URL: https://www.reddit.com/r/upsc_discussions/comments/1ws4zki/news_headlines_28_sept_2026/
Image URL: https://i.redd.it/ml4fxihav6sh1.png

------------------------------------------------------------

Published Time: 2026-09-28 04:28:38
Post Title: [Business] - Gold, Silver rate today live updates: Gold drops more than 2% as oil surge boosts US rate hike bets | Times of India
Subreddit: r/AutoNewspaper
Score: 1 (Upvote Ratio: 100%)
Author: u/AutoNewspaperAdmin
Author URL: https://www.reddit.com/user/AutoNewspaperAdmin
Post URL: https://www.reddit.com/r/AutoNewspaper/comments/1ws4ysv/business_gold_silver_rate_today_live_updates_gold/
Image URL: https://external-preview.redd.it/2mLprpd6MSdYfXeQiyUqs44v5fxi0kFRPvgQ2bfptfA.jpeg?auto=webp&s=bfbb608de19dafc533dcd5f263d359297a64e425

------------------------------------------------------------

Published Time: 2026-09-28 04:22:56
Post Title: How to Improve Warcraft 3 - Part 2: Gameplay
Subreddit: r/warcraft3
Score: 0 (Upvote Ratio: 27%)
Author: u/Ramagash
Author URL: https://www.reddit.com/user/Ramagash
Post URL: https://www.reddit.com/r/warcraft3/comments/1ws4v2c/how_to_improve_warcraft_3_part_2_gameplay/
Image URL: https://i.redd.it/sb41rnv1u6sh1.jpeg

------------------------------------------------------------

Published Time: 2026-09-28 04:18:51
Post Title: IT'S THE GREATEST EVER NEVER EVER REAL ECONOMY TIME DRIVEN BY GOLD+OIL(+GRAINS)!!!!!!!!!!!!!:)
Subreddit: r/u_SeanYun
Score: 1 (Upvote Ratio: 100%)
Author: u/SeanYun
Author URL: https://www.reddit.com/user/SeanYun
Post URL: https://www.reddit.com/r/u_SeanYun/comments/1ws4se2/its_the_greatest_ever_never_ever_real_economy/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 04:18:15
Post Title: Tamil's ,Elavenil has won 2 Silver and Baranica has won 1 bronze in the Asian Games.... Along with velavan/Joshna who got bronze in squash
Subreddit: r/TamilNaduDiscussion
Score: 15 (Upvote Ratio: 100%)
Author: u/Puzzleheaded_Ad1531
Author URL: https://www.reddit.com/user/Puzzleheaded_Ad1531
Post URL: https://www.reddit.com/r/TamilNaduDiscussion/comments/1ws4rzs/tamils_elavenil_has_won_2_silver_and_baranica_has/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 04:15:33
Post Title: Virat kohli in his last lap of his career
Subreddit: r/IndianCricket
Score: 2 (Upvote Ratio: 60%)
Author: u/vaibhav040
Author URL: https://www.reddit.com/user/vaibhav040
Post URL: https://www.reddit.com/r/IndianCricket/comments/1ws4q4x/virat_kohli_in_his_last_lap_of_his_career/

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Image: None

------------------------------------------------------------

Published Time: 2026-09-28 04:00:20
Post Title: Macro Radar — Gazzetta di Kyiv
Subreddit: r/LaGazzettadiKyiv
Score: 1 (Upvote Ratio: 100%)
Author: u/lagazzettadikyiv
Author URL: https://www.reddit.com/user/lagazzettadikyiv
Post URL: https://www.reddit.com/r/LaGazzettadiKyiv/comments/1ws4f2d/macro_radar_gazzetta_di_kyiv/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 03:58:04
Post Title: Late 20s, remote worker, loan, career shift — how much salary is actually enough to live and save without constantly feeling scared?
Subreddit: r/personalfinanceindia
Score: 9 (Upvote Ratio: 100%)
Author: u/GobiRchandran
Author URL: https://www.reddit.com/user/GobiRchandran
Post URL: https://www.reddit.com/r/personalfinanceindia/comments/1ws4dhs/late_20s_remote_worker_loan_career_shift_how_much/

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Image: None

------------------------------------------------------------

Published Time: 2026-09-28 03:55:07
Post Title: India needs to open a sports visa so Desis can play for the Indian national team because this is beyond embarrassing; Japan shocked the world
Subreddit: r/IndianCricket
Score: 0 (Upvote Ratio: 25%)
Author: u/BrownCastro14
Author URL: https://www.reddit.com/user/BrownCastro14
Post URL: https://www.reddit.com/r/IndianCricket/comments/1ws4bi3/india_needs_to_open_a_sports_visa_so_desis_can/

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Image: None

------------------------------------------------------------

Published Time: 2026-09-28 03:53:21
Post Title: Me, my name, and my faith aren’t raising the price of gas and groceries. They're not the reason you can’t see a doctor or afford a new home. That's Donald Trump, that's JD Vance, and people like Mike Rogers. - Abdul El-Sayed
Subreddit: r/thescoop
Score: 179 (Upvote Ratio: 99%)
Author: u/biospheric
Author URL: https://www.reddit.com/user/biospheric
Post URL: https://www.reddit.com/r/thescoop/comments/1ws4abl/me_my_name_and_my_faith_arent_raising_the_price/
Image URL: https://external-preview.redd.it/NDRtaHZsZHJvNnNoMfc7SQIXj_RbsmbmZvv9b-bG_om8FchHjJUCFHY6NCiZ.png?format=pjpg&auto=webp&s=908abe89c9d3e1f5527f314de1f13159cf34b25a

------------------------------------------------------------

Published Time: 2026-09-28 03:50:46
Post Title: finally got the ice cream gold sticker
Subreddit: r/balatro
Score: 20 (Upvote Ratio: 96%)
Author: u/cherrybombthegoat
Author URL: https://www.reddit.com/user/cherrybombthegoat
Post URL: https://www.reddit.com/r/balatro/comments/1ws48nd/finally_got_the_ice_cream_gold_sticker/
Image URL: https://i.redd.it/ozp35wz9o6sh1.png

------------------------------------------------------------

Published Time: 2026-09-28 03:47:41
Post Title: this game is the definition of suffering
Subreddit: r/MobileLegendsGame
Score: 6 (Upvote Ratio: 88%)
Author: u/4L3XD024
Author URL: https://www.reddit.com/user/4L3XD024
Post URL: https://www.reddit.com/r/MobileLegendsGame/comments/1ws46oq/this_game_is_the_definition_of_suffering/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 03:44:48
Post Title: last 3 i need will trade for anything lmk
Subreddit: r/SpriteTrades
Score: 1 (Upvote Ratio: 100%)
Author: u/zoro99921
Author URL: https://www.reddit.com/user/zoro99921
Post URL: https://www.reddit.com/r/SpriteTrades/comments/1ws44rv/last_3_i_need_will_trade_for_anything_lmk/
Image URL: https://i.redd.it/ge2drl79n6sh1.jpeg

------------------------------------------------------------

Published Time: 2026-09-28 03:42:14
Post Title: First Gold Victory on Dragons
Subreddit: r/PlayTheBazaar
Score: 1 (Upvote Ratio: 100%)
Author: u/RandyRenegade
Author URL: https://www.reddit.com/user/RandyRenegade
Post URL: https://www.reddit.com/r/PlayTheBazaar/comments/1ws433p/first_gold_victory_on_dragons/
Image URL: https://i.redd.it/ctgl1f5sm6sh1.png

------------------------------------------------------------

Published Time: 2026-09-28 03:40:55
Post Title: Trade??
Subreddit: r/Monopoly_GO
Score: 1 (Upvote Ratio: 100%)
Author: u/Ok-Jicama3028
Author URL: https://www.reddit.com/user/Ok-Jicama3028
Post URL: https://www.reddit.com/r/Monopoly_GO/comments/1ws428m/trade/

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Image: None

------------------------------------------------------------

Published Time: 2026-09-28 03:34:45
Post Title: What am I doing wrong??
Subreddit: r/leagueoflegends
Score: 2 (Upvote Ratio: 100%)
Author: u/GrandmasterCheetah
Author URL: https://www.reddit.com/user/GrandmasterCheetah
Post URL: https://www.reddit.com/r/leagueoflegends/comments/1ws3y3y/what_am_i_doing_wrong/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 03:30:05
Post Title: The new historical 4X turn-based strategy game Embersong: History is Yours will release September 29th!
Subreddit: r/computergaming
Score: 1 (Upvote Ratio: 100%)
Author: u/JordanMilas
Author URL: https://www.reddit.com/user/JordanMilas
Post URL: https://www.reddit.com/r/computergaming/comments/1ws3uye/the_new_historical_4x_turnbased_strategy_game/
Image URL: https://external-preview.redd.it/b25tcG16NWprNnNoMdk7hdPVXUFoOjqSffD4NQ3LZ7I76tU013DD310YQb7Q.png?format=pjpg&auto=webp&s=39c86edeb3580e0216e886cf6c404ae00d3d9d24

------------------------------------------------------------

Published Time: 2026-09-28 03:28:00
Post Title: The new historical 4X turn-based strategy game Embersong: History is Yours will release September 29th on SteamOS!
Subreddit: r/SteamdeckGames
Score: 1 (Upvote Ratio: 100%)
Author: u/JordanMilas
Author URL: https://www.reddit.com/user/JordanMilas
Post URL: https://www.reddit.com/r/SteamdeckGames/comments/1ws3tgl/the_new_historical_4x_turnbased_strategy_game/
Image URL: https://external-preview.redd.it/cWY2dDV1YjRrNnNoMdk7hdPVXUFoOjqSffD4NQ3LZ7I76tU013DD310YQb7Q.png?format=pjpg&auto=webp&s=78b285a3253957e1dd4bb3abb60a366aaff6e22f

------------------------------------------------------------

Published Time: 2026-09-28 03:24:27
Post Title: The new historical 4X turn-based strategy game Embersong: History is Yours will release September 29th on Linux and SteamOS!
Subreddit: r/linux_gaming
Score: 1 (Upvote Ratio: 54%)
Author: u/JordanMilas
Author URL: https://www.reddit.com/user/JordanMilas
Post URL: https://www.reddit.com/r/linux_gaming/comments/1ws3r19/the_new_historical_4x_turnbased_strategy_game/
Image URL: https://external-preview.redd.it/bDQ2ZGFvcHhpNnNoMdk7hdPVXUFoOjqSffD4NQ3LZ7I76tU013DD310YQb7Q.png?format=pjpg&auto=webp&s=419c761576902dee430f4c4bf07dd116b3aec19b

------------------------------------------------------------

Published Time: 2026-09-28 03:20:49
Post Title: Korath Plus v0.2.0 — Deck Randomizer, Endless Mode, Recycling Dungeons, Shop Replenish, and a full Mod Manager
Subreddit: r/Shandalar
Score: 20 (Upvote Ratio: 100%)
Author: u/chachaprince1
Author URL: https://www.reddit.com/user/chachaprince1
Post URL: https://www.reddit.com/r/Shandalar/comments/1ws3oki/korath_plus_v020_deck_randomizer_endless_mode/

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Image: None

------------------------------------------------------------

Published Time: 2026-09-28 03:20:24
Post Title: WOW!!!!!:) KATAYAMA OBASAN!!!!!!!:) AS I'VE ADVISED THAT TALK TO PM TAKAICHI JAPAN MUST HAVE ITS OWN NUKES SAME AS USA+CHINA+EUROPE+ISRAEL+ N KOREA+INDIA+PAKISTAN ETC TO SURVIVE OR NO PROBABILITY TO SURVIVE THE SOVEREIGNTY OF THE COUNTRY<--- THIS IS REALITY!!!!!!:) YOU KNOW WHAT I MEAN?!!!!!!:)
Subreddit: r/u_SeanYun
Score: 1 (Upvote Ratio: 100%)
Author: u/SeanYun
Author URL: https://www.reddit.com/user/SeanYun
Post URL: https://www.reddit.com/r/u_SeanYun/comments/1ws3o9j/wow_katayama_obasan_as_ive_advised_that_talk_to/
Image URL: https://external-preview.redd.it/OHBldWo2MHRpNnNoMeuG1WN11AaPOl3NjHqLMUzSP4uhv8SPk66LUfGD4uHd.png?format=pjpg&auto=webp&s=d6e1c65b715560ac39b50a758c749f6ca8e7db6d

------------------------------------------------------------

Published Time: 2026-09-28 03:19:16
Post Title: this
Subreddit: r/u_Parth_NB
Score: 2 (Upvote Ratio: 100%)
Author: u/Parth_NB
Author URL: https://www.reddit.com/user/Parth_NB
Post URL: https://www.reddit.com/r/u_Parth_NB/comments/1ws3ngu/this/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 03:17:20
Post Title: This synergy is messy but insane and I’ve got a foil brainstorm in the shop, what do I do?
Subreddit: r/balatro
Score: 2 (Upvote Ratio: 76%)
Author: u/WhyAm_I_SoTired
Author URL: https://www.reddit.com/user/WhyAm_I_SoTired
Post URL: https://www.reddit.com/r/balatro/comments/1ws3m3z/this_synergy_is_messy_but_insane_and_ive_got_a/

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Image: None

------------------------------------------------------------

Published Time: 2026-09-28 03:15:53
Post Title: last ones who wanna trade ?!
Subreddit: r/FortniteSpriteTrades
Score: 2 (Upvote Ratio: 100%)
Author: u/zoro99921
Author URL: https://www.reddit.com/user/zoro99921
Post URL: https://www.reddit.com/r/FortniteSpriteTrades/comments/1ws3l2t/last_ones_who_wanna_trade/
Image URL: https://i.redd.it/j7ztmrg3i6sh1.jpeg

------------------------------------------------------------

Published Time: 2026-09-28 03:15:32
Post Title: Lầu Năm Góc từ chối chi trả tiền bồi thường cho các binh sĩ thiệt mạng trong cuộc xung đột với Iran vì "đó không phải là chiến tranh"
Subreddit: r/VietNamNation
Score: 0 (Upvote Ratio: 40%)
Author: u/Fine-Camp-2839
Author URL: https://www.reddit.com/user/Fine-Camp-2839
Post URL: https://www.reddit.com/r/VietNamNation/comments/1ws3ktz/lầu_năm_góc_từ_chối_chi_trả_tiền_bồi_thường_cho/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 03:07:42
Post Title: 20th Asian Games medal tally as 11:06 a.m., Sept. 28, 2026
Subreddit: r/newsPH
Score: 3 (Upvote Ratio: 100%)
Author: u/TheManilaTimes
Author URL: https://www.reddit.com/user/TheManilaTimes
Post URL: https://www.reddit.com/r/newsPH/comments/1ws3fdc/20th_asian_games_medal_tally_as_1106_am_sept_28/
Image URL: https://i.redd.it/lufbyctlg6sh1.jpeg

------------------------------------------------------------

Published Time: 2026-09-28 03:06:58
Post Title: 📢 Bitget Weekly Updates: Highlights from the Past Week 👑
Subreddit: r/BitgetReddit
Score: 1 (Upvote Ratio: 100%)
Author: u/Tinabitget
Author URL: https://www.reddit.com/user/Tinabitget
Post URL: https://www.reddit.com/r/BitgetReddit/comments/1ws3eup/bitget_weekly_updates_highlights_from_the_past/
Image URL: https://i.redd.it/6npcsr5hg6sh1.jpeg

------------------------------------------------------------

Published Time: 2026-09-28 02:59:58
Post Title: Reddit creates a fictional country (set in the real world) - day 7, what should it's coat of arms be?
Subreddit: r/dailygames
Score: 1 (Upvote Ratio: 100%)
Author: u/Objective-Neck9275
Author URL: https://www.reddit.com/user/Objective-Neck9275
Post URL: https://www.reddit.com/r/dailygames/comments/1ws39jp/reddit_creates_a_fictional_country_set_in_the/
Image URL: https://i.redd.it/6yi4p559f6sh1.png

------------------------------------------------------------

Published Time: 2026-09-28 02:59:13
Post Title: Against the Current episodes 34-35 discussion 💣💣💣
Subreddit: r/CDrama
Score: 70 (Upvote Ratio: 99%)
Author: u/Lotus_swimmer
Author URL: https://www.reddit.com/user/Lotus_swimmer
Post URL: https://www.reddit.com/r/CDrama/comments/1ws390p/against_the_current_episodes_3435_discussion/
Image URL: https://i.redd.it/572ii11ye6sh1.gif

------------------------------------------------------------

Published Time: 2026-09-28 02:53:58
Post Title: How India is handling the Strait of Hormuz crisis - a report by ET
Subreddit: r/CriticalThinkingIndia
Score: 19 (Upvote Ratio: 79%)
Author: u/Immediate-Humor-6077
Author URL: https://www.reddit.com/user/Immediate-Humor-6077
Post URL: https://www.reddit.com/r/CriticalThinkingIndia/comments/1ws35c1/how_india_is_handling_the_strait_of_hormuz_crisis/
Image URL: https://external-preview.redd.it/ajRrZGhjYTZlNnNoMcG7bDfFn0TT9ww9r-oKpTs3U4teNJLtltc9pxIR9paT.jpeg?format=pjpg&auto=webp&s=0d0a8ca4e1fa61789c2e5a7799d9b0d0bcc5855b

------------------------------------------------------------

Published Time: 2026-09-28 02:52:57
Post Title: India shines at the 46th FIDE Chess Olympiad! 🇮🇳
Subreddit: r/BharatiyaJanataParty
Score: 3 (Upvote Ratio: 100%)
Author: u/CalmlyPassionate
Author URL: https://www.reddit.com/user/CalmlyPassionate
Post URL: https://www.reddit.com/r/BharatiyaJanataParty/comments/1ws34m3/india_shines_at_the_46th_fide_chess_olympiad/
Image URL: https://i.redd.it/n41li8yzd6sh1.jpeg

------------------------------------------------------------

Published Time: 2026-09-28 02:52:06
Post Title: Will these work well together?
Subreddit: r/buildapc
Score: 1 (Upvote Ratio: 100%)
Author: u/Horror-Silver8987
Author URL: https://www.reddit.com/user/Horror-Silver8987
Post URL: https://www.reddit.com/r/buildapc/comments/1ws3413/will_these_work_well_together/

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Image: None

------------------------------------------------------------

Published Time: 2026-09-28 02:49:53
Post Title: “After weeks, I’m finally about to beat my Gold Stake Win Streak Record! This run was hard but we adapted, nothing is going to go wro-“
Subreddit: r/balatro
Score: 101 (Upvote Ratio: 99%)
Author: u/Bekenshi
Author URL: https://www.reddit.com/user/Bekenshi
Post URL: https://www.reddit.com/r/balatro/comments/1ws32h7/after_weeks_im_finally_about_to_beat_my_gold/
Image URL: https://external-preview.redd.it/bW14eDR4cWZkNnNoMUi7s940rG1r2L5fpuHKWvd7wdBZLAAgTav24HRPIgN3.jpeg?format=pjpg&auto=webp&s=a6283aaf152e8aaf87ad6e5c5b8150605c511594

------------------------------------------------------------

Published Time: 2026-09-28 02:43:54
Post Title: Event: Cursed Clear (Sep. 29-30, 2026) - Disney Emoji Blitz
Subreddit: r/disneyemojiblitz
Score: 23 (Upvote Ratio: 100%)
Author: u/EmojiBlitzerGurl
Author URL: https://www.reddit.com/user/EmojiBlitzerGurl
Post URL: https://www.reddit.com/r/disneyemojiblitz/comments/1ws2ybh/event_cursed_clear_sep_2930_2026_disney_emoji/
Image URL: https://i.redd.it/witeean6c6sh1.jpeg

------------------------------------------------------------

Published Time: 2026-09-28 02:39:33
Post Title: XAUUSD
Subreddit: r/Forexstrategy
Score: 10 (Upvote Ratio: 100%)
Author: u/ykar648
Author URL: https://www.reddit.com/user/ykar648
Post URL: https://www.reddit.com/r/Forexstrategy/comments/1ws2vcr/xauusd/
Image URL: https://i.redd.it/k0ktdczlb6sh1.jpeg

------------------------------------------------------------

Published Time: 2026-09-28 02:36:55
Post Title: rajesh kazhipurath
Subreddit: r/dalalstreetbets
Score: 1 (Upvote Ratio: 100%)
Author: u/ykar648
Author URL: https://www.reddit.com/user/ykar648
Post URL: https://www.reddit.com/r/dalalstreetbets/comments/1ws2tia/rajesh_kazhipurath/
Image URL: https://external-preview.redd.it/7r2ejLzIFphhJe9cqFhYQrF8ZFENlYgtw4KepVsPmAw.jpeg?auto=webp&s=937d053bad1cfc2e0ad3aa7076715ac12482771e

------------------------------------------------------------

Published Time: 2026-09-28 02:34:37
Post Title: Some winners of WorldSkills 2026 held in Shanghai
Subreddit: r/aznidentity
Score: 25 (Upvote Ratio: 100%)
Author: u/ding_nei_go_fei
Author URL: https://www.reddit.com/user/ding_nei_go_fei
Post URL: https://www.reddit.com/r/aznidentity/comments/1ws2rz1/some_winners_of_worldskills_2026_held_in_shanghai/
Image: None

------------------------------------------------------------

Published Time: 2026-09-28 02:32:02
Post Title: CHANCE Indian Intl. applying Dartmouth ED, Engineering Sciences (RD: T20/T10+HYPSM)
Subreddit: r/chanceme
Score: 2 (Upvote Ratio: 100%)
Author: u/CatchPsychological95
Author URL: https://www.reddit.com/user/CatchPsychological95
Post URL: https://www.reddit.com/r/chanceme/comments/1ws2q5j/chance_indian_intl_applying_dartmouth_ed/

WARNING:praw:It appears that you are using PRAW in an asynchronous environment.
It is strongly recommended to use Async PRAW: https://asyncpraw.readthedocs.io.
See https://praw.readthedocs.io/en/latest/getting_started/multiple_instances.html#discord-bots-and-asynchronous-environments for more info.

Image: None

------------------------------------------------------------

Published Time: 2026-09-28 02:31:46
Post Title: Best custom black volleyball jerseys websites
Subreddit: r/Customjerseyspro
Score: 1 (Upvote Ratio: 100%)
Author: u/fashioncustom
Author URL: https://www.reddit.com/user/fashioncustom
Post URL: https://www.reddit.com/r/Customjerseyspro/comments/1ws2pyy/best_custom_black_volleyball_jerseys_websites/
Image URL: https://external-preview.redd.it/EBGZJNTa6m5jk_ykg5YQDcz48AcaG24_Czn_FJotGQU.jpeg?auto=webp&s=85414a0813f4d2a9177b3311ea9ee38285c45d84

------------------------------------------------------------

Published Time: 2026-09-28 02:30:47
Post Title: India Ranks 10th at World Skills Shanghai 2026, Wins 6 Silver Medals and 20 Medal for Excellence.
Subreddit: r/BharatiyaJanataParty
Score: 2 (Upvote Ratio: 100%)
Author: u/CalmlyPassionate
Author URL: https://www.reddit.com/user/CalmlyPassionate
Post URL: https://www.reddit.com/r/BharatiyaJanataParty/comments/1ws2pap/india_ranks_10th_at_world_skills_shanghai_2026/
Image: None

------------------------------------------------------------

✅ Reddit posts successfully saved to 'reddit.csv'

--- Reddit DataFrame ---

,Published Time,Post Title,Subreddit,Score,Upvote Ratio (%),Author,Author URL,Post URL,Post Text,Image URL
0,2026-09-28 07:58:05,"📊 NordFX: Quarter-End Test - JOLTS, PCE, USD a...",NordFX,1,100,Marketing_NordFX,https://www.reddit.com/user/Marketing_NordFX,https://www.reddit.com/r/NordFX/comments/1ws8i...,🔥 **Can gold regain its footing as the dollar ...,https://external-preview.redd.it/ODNnbmoweGV3N...
1,2026-09-28 07:50:40,After using a GTX 1060 mobile since it came I ...,gamesuggestions,2,100,AtmosphereBlue,https://www.reddit.com/user/AtmosphereBlue,https://www.reddit.com/r/gamesuggestions/comme...,I finally have a new PC which has the RTX 5070...,None
2,2026-09-28 07:46:39,[Business] - Gold price prediction: What are t...,MetalsOnReddit,1,100,Then_Marionberry_259,https://www.reddit.com/user/Then_Marionberry_259,https://www.reddit.com/r/MetalsOnReddit/commen...,None,https://external-preview.redd.it/iHSGbIRF4mQhB...
3,2026-09-28 07:44:10,Mahanirvana Tantra Chapter 9 Part 6,TantraMarg,2,100,Straight-Cable433,https://www.reddit.com/user/Straight-Cable433,https://www.reddit.com/r/TantraMarg/comments/1...,MAHANIRVANA TANTRA CHAPTER IX: THE TEN SAMSKA...,https://i.redd.it/um9qciiyt7sh1.jpeg
4,2026-09-28 07:37:21,Got scammed by Zevana - “India’s most trusted ...,indianbeautyyappers,2,100,Effective_Lawyer_647,https://www.reddit.com/user/Effective_Lawyer_647,https://www.reddit.com/r/indianbeautyyappers/c...,Zevana claims to be India’s most trusted desti...,None
...,...,...,...,...,...,...,...,...,...,...
95,2026-09-28 02:36:55,rajesh kazhipurath,dalalstreetbets,1,100,ykar648,https://www.reddit.com/user/ykar648,https://www.reddit.com/r/dalalstreetbets/comme...,US long-term borrowing costs are flashing a wa...,https://external-preview.redd.it/7r2ejLzIFphhJ...
96,2026-09-28 02:34:37,Some winners of WorldSkills 2026 held in Shanghai,aznidentity,24,100,ding_nei_go_fei,https://www.reddit.com/user/ding_nei_go_fei,https://www.reddit.com/r/aznidentity/comments/...,WorldSkills now in it's 48th year is a competi...,None
97,2026-09-28 02:32:02,"CHANCE Indian Intl. applying Dartmouth ED, Eng...",chanceme,2,100,CatchPsychological95,https://www.reddit.com/user/CatchPsychological95,https://www.reddit.com/r/chanceme/comments/1ws...,"**Demographics:** * Indian, male, internation...",None
98,2026-09-28 02:31:46,Best custom black volleyball jerseys websites,Customjerseyspro,1,100,fashioncustom,https://www.reddit.com/user/fashioncustom,https://www.reddit.com/r/Customjerseyspro/comm...,Looking to customize a black volleyball jersey...,https://external-preview.redd.it/EBGZJNTa6m5jk...
99,2026-09-28 02:30:47,India Ranks 10th at World Skills Shanghai 2026...,BharatiyaJanataParty,2,100,CalmlyPassionate,https://www.reddit.com/user/CalmlyPassionate,https://www.reddit.com/r/BharatiyaJanataParty/...,India moves up from 13th position at World Ski...,None

# **Data Preprocessing**

**Real News**

In [7]:
df

,Published Time,Title,Description,Image URL,Content,Source Name,Source URL,Source Country,Article URL
0,2026-09-27T08:47:17Z,"""I still can't believe it"": Prachi Choudhary a...",Prachi Choudhary claimed the bronze with a tim...,https://www.tribuneindia.com/sortd-service/ima...,"New Delhi [India], September 27 (ANI): India a...",The Tribune,https://www.tribuneindia.com,in,https://www.tribuneindia.com/news/sports/i-sti...
1,2026-09-27T08:45:34Z,"""I still can't believe it"": Prachi Choudhary a...",Prachi Choudhary claimed the bronze with a tim...,https://d3lzcn6mbbadaf.cloudfront.net/media/de...,"New Delhi [India], September 27 (ANI): India a...",ANI (Asian News International),https://www.aninews.in,in,https://www.aninews.in/news/sports/others/i-st...
2,2026-09-26T17:10:25Z,India Beat Iran In Both Kabaddi Finals To Win ...,India completed a kabaddi golden double at the...,https://sm.mashable.com/mashable_in/seo/defaul...,India completed a golden double in kabaddi at ...,Mashable India,https://in.mashable.com,in,https://in.mashable.com/sports/114326/india-be...
3,2026-09-26T13:51:00Z,India maintain choke-hold on Asiad Kabaddi gol...,India's kabaddi teams delivered stellar perfor...,"https://img.etimg.com/thumb/msid-134505784,wid...",Synopsis\nIndia's kabaddi teams delivered stel...,The Economic Times,https://economictimes.indiatimes.com,in,https://economictimes.indiatimes.com/news/spor...
4,2026-09-26T12:52:34Z,Prachi Choudhary Win Bronze In Women's 400m Fo...,Salwa Naser of Bahrain bagged the gold medal w...,https://images.news18.com/ibnlive/uploads/2026...,"Last Updated:September 26, 2026, 18:27 IST\nSa...",News18,https://www.news18.com,in,https://www.news18.com/sports/other-sports/pra...

**BlueSky News**

In [24]:
df_bluesky

,Published Time,Post Text,Author Name,Author Handle,Author DID,Author Profile Image,Author URL,Post URL,Likes,Reposts,Replies,Quotes
0,2026-09-26T17:10:25.000Z,,Mashable India [Unofficial],in.mashable.com.web.brid.gy,did:plc:tkzj743ruh5itf2pov2q5txv,https://cdn.bsky.app/img/avatar/plain/did:plc:...,https://bsky.app/profile/in.mashable.com.web.b...,https://bsky.app/profile/in.mashable.com.web.b...,0,0,0,0
1,2026-09-26T16:07:43Z,Asian Games 2026 Day 7: India win seven medals...,HFG INSIDER,health897.bsky.social,did:plc:euogifoh4mj52xvkbqcfqtti,https://cdn.bsky.app/img/avatar/plain/did:plc:...,https://bsky.app/profile/health897.bsky.social,https://bsky.app/profile/health897.bsky.social...,0,0,0,0
2,2026-09-26T10:55:45.726Z,India beat Iran to win ninth Gold medal in men...,,newsinc24.bsky.social,did:plc:6qomd7wrtbnrjq5p3cww7fuc,https://cdn.bsky.app/img/avatar/plain/did:plc:...,https://bsky.app/profile/newsinc24.bsky.social,https://bsky.app/profile/newsinc24.bsky.social...,0,0,0,0
3,2026-09-26T09:36:23.000Z,,Mashable India [Unofficial],in.mashable.com.web.brid.gy,did:plc:tkzj743ruh5itf2pov2q5txv,https://cdn.bsky.app/img/avatar/plain/did:plc:...,https://bsky.app/profile/in.mashable.com.web.b...,https://bsky.app/profile/in.mashable.com.web.b...,0,0,0,0
4,2026-09-25T18:59:24Z,Asian Games 2026 Kabaddi: India Storm Into Men...,,newsarea.bsky.social,did:plc:kqj4vuyjvmtnptvvdt2xijtk,https://cdn.bsky.app/img/avatar/plain/did:plc:...,https://bsky.app/profile/newsarea.bsky.social,https://bsky.app/profile/newsarea.bsky.social/...,0,0,0,0
5,2026-09-25T07:18:03Z,Asian Games 2026 Day 6: Suruchi Singh and Kama...,,navroze-india.bsky.social,did:plc:nndhrtds5t6ipm4zdvov6php,https://cdn.bsky.app/img/avatar/plain/did:plc:...,https://bsky.app/profile/navroze-india.bsky.so...,https://bsky.app/profile/navroze-india.bsky.so...,0,0,0,0
6,2026-06-22T21:24:44.002Z,🗞️ Friday Finance #35 is live! This week: bill...,sam's friday finance weekly-ish,fridayfinance.bsky.social,did:plc:mb3dgo74f2yssbnccjfh4g6z,https://cdn.bsky.app/img/avatar/plain/did:plc:...,https://bsky.app/profile/fridayfinance.bsky.so...,https://bsky.app/profile/fridayfinance.bsky.so...,0,0,1,0
7,2025-10-23T14:57:32.319Z,India are the first girls' champs in kabaddi's...,Archive,archive041716.bsky.social,did:plc:de2ulpepjaul36mazt33vvdf,https://cdn.bsky.app/img/avatar/plain/did:plc:...,https://bsky.app/profile/archive041716.bsky.so...,https://bsky.app/profile/archive041716.bsky.so...,0,0,0,0
8,2025-08-25T09:01:05.356020+00:00,"Feed: ""Neptune Prime""\nBy: Maryam Sulaiman Abu...",Longtail News,longtail-news.bsky.social,did:plc:o6ggjvnj4ze3mnrpnv5oravg,https://cdn.bsky.app/img/avatar/plain/did:plc:...,https://bsky.app/profile/longtail-news.bsky.so...,https://bsky.app/profile/longtail-news.bsky.so...,0,0,0,0

**Reddit News**

In [25]:
df_reddit

,Published Time,Post Title,Subreddit,Score,Upvote Ratio (%),Author,Author URL,Post URL,Post Text,Image URL
0,2026-09-28 07:58:05,"📊 NordFX: Quarter-End Test - JOLTS, PCE, USD a...",NordFX,1,100,Marketing_NordFX,https://www.reddit.com/user/Marketing_NordFX,https://www.reddit.com/r/NordFX/comments/1ws8i...,🔥 **Can gold regain its footing as the dollar ...,https://external-preview.redd.it/ODNnbmoweGV3N...
1,2026-09-28 07:50:40,After using a GTX 1060 mobile since it came I ...,gamesuggestions,2,100,AtmosphereBlue,https://www.reddit.com/user/AtmosphereBlue,https://www.reddit.com/r/gamesuggestions/comme...,I finally have a new PC which has the RTX 5070...,None
2,2026-09-28 07:46:39,[Business] - Gold price prediction: What are t...,MetalsOnReddit,1,100,Then_Marionberry_259,https://www.reddit.com/user/Then_Marionberry_259,https://www.reddit.com/r/MetalsOnReddit/commen...,None,https://external-preview.redd.it/iHSGbIRF4mQhB...
3,2026-09-28 07:44:10,Mahanirvana Tantra Chapter 9 Part 6,TantraMarg,2,100,Straight-Cable433,https://www.reddit.com/user/Straight-Cable433,https://www.reddit.com/r/TantraMarg/comments/1...,MAHANIRVANA TANTRA CHAPTER IX: THE TEN SAMSKA...,https://i.redd.it/um9qciiyt7sh1.jpeg
4,2026-09-28 07:37:21,Got scammed by Zevana - “India’s most trusted ...,indianbeautyyappers,2,100,Effective_Lawyer_647,https://www.reddit.com/user/Effective_Lawyer_647,https://www.reddit.com/r/indianbeautyyappers/c...,Zevana claims to be India’s most trusted desti...,None
...,...,...,...,...,...,...,...,...,...,...
95,2026-09-28 02:36:55,rajesh kazhipurath,dalalstreetbets,1,100,ykar648,https://www.reddit.com/user/ykar648,https://www.reddit.com/r/dalalstreetbets/comme...,US long-term borrowing costs are flashing a wa...,https://external-preview.redd.it/7r2ejLzIFphhJ...
96,2026-09-28 02:34:37,Some winners of WorldSkills 2026 held in Shanghai,aznidentity,24,100,ding_nei_go_fei,https://www.reddit.com/user/ding_nei_go_fei,https://www.reddit.com/r/aznidentity/comments/...,WorldSkills now in it's 48th year is a competi...,None
97,2026-09-28 02:32:02,"CHANCE Indian Intl. applying Dartmouth ED, Eng...",chanceme,2,100,CatchPsychological95,https://www.reddit.com/user/CatchPsychological95,https://www.reddit.com/r/chanceme/comments/1ws...,"**Demographics:** * Indian, male, internation...",None
98,2026-09-28 02:31:46,Best custom black volleyball jerseys websites,Customjerseyspro,1,100,fashioncustom,https://www.reddit.com/user/fashioncustom,https://www.reddit.com/r/Customjerseyspro/comm...,Looking to customize a black volleyball jersey...,https://external-preview.redd.it/EBGZJNTa6m5jk...
99,2026-09-28 02:30:47,India Ranks 10th at World Skills Shanghai 2026...,BharatiyaJanataParty,2,100,CalmlyPassionate,https://www.reddit.com/user/CalmlyPassionate,https://www.reddit.com/r/BharatiyaJanataParty/...,India moves up from 13th position at World Ski...,None

# **Model Development**